ubuntu/yaru_widgets.dart

- example/lib/yaru_master_details_page.dart
- lib/src/material/LICENSE
- lib/src/material/yaru_checkbox.dart
- lib/yaru_widgets.dart
Add a new `YaruCheckbox` widget, fully compatible with the material one.
https://user-images.githubusercontent.com/36476595/145389440-d00dde0a-ea1c-400c-905b-e68e467a8267.mp4
I copied the code of the material `Checkbox` and I tweaked the icon drawing function, and the size. You can see all changes I did with `// Yaru change` comments (just like the Yaru repository, I'll add later an action which will check upstream change).
The benefit of tweaking the code upstream is:
- it is fully compatible with the material `Checkbox`, and so we can replace each previous with a `YaruCheckbox` without any problem ;
- we keep the same look and feel as the material `Checkbox`: check animation, splash, ...
> Add YaruCheckbox Material based widget

- lib/src/yaru_simple_dialog.dart
Decrease YaruSimpleDialog close button `splashRadius` to 16.
Closes #32
> Decrease YaruSimpleDialog close button splashRadius

- example/lib/widgets/yaru_row_list.dart
- example/lib/yaru_home.dart
- lib/src/yaru_checkbox_row.dart
- lib/src/yaru_extra_option_row.dart
- lib/src/yaru_option_button.dart
- lib/src/yaru_row.dart
- lib/src/yaru_single_info_row.dart
- lib/src/yaru_slider_row.dart
- lib/src/yaru_switch_row.dart
- lib/src/yaru_toggle_buttons_row.dart
- test/yaru_check_box_row_test.dart
- test/yaru_extra_options_row_test.dart
- test/yaru_row_test.dart
- test/yaru_switch_row_test.dart
- test/yaru_togggle_button_row_test.dart
As discussed here: https://github.com/Feichtmeier/settings/issues/1982 I made some changes to allow widgets to look disabled instead of displaying empty SizedBoxes when there's no value.
> Disable instead hide

- example/lib/widgets/yaru_option_card_list.dart
- example/lib/yaru_home.dart
- lib/src/constants.dart
- lib/src/yaru_landscape_layout.dart
- lib/src/yaru_page.dart
- lib/src/yaru_page_item.dart
- lib/src/yaru_portrait_layout.dart
- lib/src/yaru_tabbed_page.dart
- lib/yaru_widgets.dart
- YaruPageItems now have an optional wrapInScrollView field which is used in both Portrait and Landscape layout to decided if one wants to wrap the item in yet another scrollview because this is not always needed and often harms the whole situation of adding unpredicted content to a page
- YaruPageItems also make the padding optional so each page has more freedom
- YaruTabbedPage now does not include SingleChildScrollview but expands the bottom content so the tab header stays even if the bottom content is scrollable
- updated the example to visualize this better
- updated the example to expand option cards
- remove height from YaruTabbedPage
- make the width of YaruTabbedPage optional so one can decide if the tabs should expand to the parent width or not
> Fixes for scrollable content

- example/lib/alternative_main.dart
- example/lib/widgets/list_yaru_options.dart
- example/lib/widgets/yaru_option_card_list.dart
- example/lib/widgets/yaru_row_list.dart
- example/lib/yaru_home.dart
- example/pubspec.yaml
- lib/src/yaru_narrow_layout.dart
- lib/src/yaru_wide_layout.dart
- lib/yaru_widgets.dart
When one has many YaruPageItems the YaruMasterDetailsPage is a great choice for both 600+ windows and windows <= 600 pixels.
However sometimes you do not want to navigate back to the list of YaruPageItems and instead want a bottom navigation bar. Especially when you only have 3-10 items.
That's why I am adding two additional, much simpler layouts
YaruNarrowLayout, which includes a bottom navigation bar, which can be combined with
YaruWideLayout, which includes a navigation rail
Both can be combined with a searchbar but do not have to. But both need YaruPageItems to create the corresponding views and menu items.
> Add an alternative layout

- example/lib/yaru_home.dart
- lib/src/yaru_alert_dialog.dart
Since we have YaruDialogTitle which includes our desired styling and close button, we should not force the AlertDialog into a certain content.
This removes content padding and the column inside to let us chose whatever content we like. If it is something standartized we can just insert a YaruPage and it already looks good out of the box.
> YaruAlertDialog: more freedom for the content

- README.md
Thanks for creating this package :)
Although the file `.github/images/screenshot_dark.png` is displayed correctly on [GitHub](https://github.com/ubuntu/yaru_widgets.dart#readme), it is not displayed correctly on [pub.dev](https://pub.dev/packages/yaru_widgets). By using a raw link, this image will be displayed correctly on both websites.
Feel free to close if you feel it is not applicable. However, I believe other developers would benefit from seeing a screenshot on pub.dev.
> Bugfix/screenshot path in README

- example/lib/main.dart
- lib/src/yaru_search_app_bar.dart
- if the theme does not specify an appbar height, the searchappbar defaults to the material constant kToolbarHeight
Not specified:
Specified:
> YaruSearchAppBar: default to theme's appbar height

- example/lib/main.dart
- lib/src/yaru_landscape_layout.dart
- lib/src/yaru_master_detail_page.dart
- lib/src/yaru_portrait_layout.dart
- lib/src/yaru_search_app_bar.dart
This removes the hardcoded search bar from YaruMasterDetails / Landscape / Portrait layout
If needed everything can be defined top down, for example with a yaru searchbar but any widget is possible now. This will be useful when yaru widgets will be used for other desktop apps, like a file explorer.
This leaves also room for design without appbars if wanted:
Closes #85
> Remove hardcoded search

- example/lib/main.dart
- lib/src/yaru_portrait_layout.dart
- lib/src/yaru_search_app_bar.dart
- uses an IconButton for the clear-search-button
- adds the material kToolbarHeight as the default height, this is needed if the YaruSearchAppBar is put into a container that is unconstrained.
> YaruSearchAppBar: height and button fixes 

- example/lib/example_page_items.dart
- example/lib/pages/carousel_page.dart
- example/linux/flutter/generated_plugins.cmake
- lib/src/yaru_carousel.dart
https://user-images.githubusercontent.com/15329494/155174045-c6dbe33a-1611-4c60-b0c9-7bb2c9ea1079.mp4
> YaruCarousel: put indicator dots in expanded

- lib/src/yaru_carousel.dart
Allow to navigate into a `YaruCarousel` by clicking on a page or a circle.
https://user-images.githubusercontent.com/36476595/168139706-56d9b3fe-b27c-44ef-b1f2-4ec4a7a16481.mp4
> YaruCarousel: allow more actions

- lib/src/yaru_selectable_container.dart
The inner border-radius shouldn't use the same value as the outer one.
It needs to be computed with the padding.
**Before:**
**After:**
> YaruSelectableContainer fix inner border-radius

- lib/src/yaru_carousel.dart
IMO, having an unique dot is a bit weird:
So let hide the indicator if child length = 1.
> YaruCarousel: auto hide indicator if child length = 1

- lib/src/yaru_carousel.dart
Use a size transform animation instead of the animated margin property, to avoid weird effect with text child.
**Before:**
https://user-images.githubusercontent.com/36476595/169053393-d89bfffd-bc86-4b95-a4e2-77cf7122df0c.mp4
**After:**
https://user-images.githubusercontent.com/36476595/169053460-e61aa403-5b6d-4d2b-8fe6-74e1d76d9686.mp4
> YaruCarousel: use size transform animation

- lib/src/yaru_carousel.dart
**Before:**
The first page show 0 and the last one indicate the length - 1.
**After:**
> YaruCarousel: fix text indicator

- lib/src/yaru_carousel.dart
> YaruCarousel: use grey for unselected dots

- example/lib/pages/carousel_page.dart
- lib/src/yaru_carousel.dart
> YaruCarousel: add navigation controls

- example/lib/example_page_items.dart
- example/lib/pages/draggable_page.dart
- lib/src/yaru_draggable.dart
- lib/yaru_widgets.dart
https://user-images.githubusercontent.com/36476595/171051765-a68b46fc-b5d4-4e7d-9dea-88561acb774c.mp4
Will certainly be very useful for creating the screen layout widget of "Settings".
> Introduce YaruDraggable widget

- lib/src/yaru_dialog_title.dart
They changed icon buttons to look like a pill rather than a disk. This replaces the icon button with an inkwell to be independent of material3
| --- | --- |
| ![grafik](https://user-images.githubusercontent.com/15329494/173196360-dd75b978-38a3-4b28-849e-1b0bfedd3ab4.png) | ![grafik](https://user-images.githubusercontent.com/15329494/173196315-c9e58602-f76f-479f-8316-59b6f42c6d01.png) |
> YaruDialogTitle: fix for material3

- example/lib/example_page_items.dart
- example/lib/main.dart
- lib/src/yaru_page_item.dart
- lib/src/yaru_page_item_title.dart
- lib/yaru_widgets.dart
Add a new `YaruPageItemTitle` widget, which alter the current text style with:
- `maxLines`: **1**
- `overflow`: `TextOverflow.ellipsis`
You can pass a child widget, or directly a string with the `YaruPageItemTitle.text` constructor.
**Before:**
**After:**
Closes #174
> Add new YaruPageItemTitle widget

- lib/src/extensions/inner_border_radius.dart
- lib/src/utilities/yaru_banner.dart
- lib/src/utilities/yaru_selectable_container.dart
@Feichtmeier Do you think we can export the extension? I think this can be useful in many contexts.
Fixes #186
> YaruBanner: adapt inner to outer border radius

- example/lib/pages/tabbed_page_page.dart
- lib/src/utilities/yaru_banner.dart
- Inkwells paint over everything else if not wrap inside material this is problematic when used inside scrollviews
|Before|After|
|-|-|
|![grafik](https://user-images.githubusercontent.com/15329494/187384509-4bc4d18b-5a00-4ec3-9122-f2c51ad1a233.png)|![grafik](https://user-images.githubusercontent.com/15329494/187384612-cc8e5d4b-cabc-43ae-b5c9-f7c105f580ab.png)|
Ref https://github.com/ubuntu-flutter-community/software/issues/121
> YaruBanner: wrap inkwell in material for  zindex

- lib/src/pages/layouts/yaru_wide_layout.dart
- lib/src/utilities/yaru_banner.dart
Fix those deprecations from Flutter 3.3:
- info • 'backgroundColor' is deprecated and shouldn't be used. Use colorScheme.background instead. This feature was deprecated after v3.3.0-0.5.pre. • lib/src/pages/layouts/yaru_wide_layout.dart:90:62 • deprecated_member_use
- info • 'backgroundColor' is deprecated and shouldn't be used. Use colorScheme.background instead. This feature was deprecated after v3.3.0-0.5.pre. • lib/src/utilities/yaru_banner.dart:115:41 • deprecated_member_use
> Fix Flutter 3.3 deprecations

- example/lib/main.dart
- lib/src/pages/layouts/yaru_compact_layout.dart
- lib/src/pages/layouts/yaru_wide_layout.dart
Useful for widescreens
Will be replaced when #201 lands
https://user-images.githubusercontent.com/15329494/190858408-710f75a2-1d71-41c1-aa15-af9111a5420a.mp4
> CompactLayout: expose extended property

- example/lib/pages/carousel_page.dart
- example/lib/widgets/option_button_list.dart
- lib/src/controls/yaru_option_button.dart
- lib/src/pages/rows/yaru_extra_option_row.dart
- test/controls/yaru_options_button_test.dart
Allow passing an arbitrary widget without limiting it to an Icon, and set the desired icon size via IconTheme. This allows passing an SVG or wrapping the icon with a badge, for example.
> YaruOptionButton: replace iconData with a child widget

- example/lib/pages/banner_page.dart
- example/lib/pages/tabbed_page_page.dart
- lib/src/utilities/yaru_banner.dart
The software app can pass SafeNetworkImage from the outside. For example:
```diff
child: YaruBanner(
name: snap.name,
summary: snap.summary,
-  url: snap.iconUrl,
+  icon: SafeNetworkImage(
+    url: snap.iconUrl,
+    fallBackIconData: YaruIcons.package_snap,
+  ),
onTap: () => model.selectedSnap = snap,
-  fallbackIconData: YaruIcons.package_snap,
),
```
> YaruBanner: remove fallback icon / safe network image

- example/lib/pages/carousel_page.dart
- lib/src/utilities/yaru_carousel.dart
This allow to control it from anywhere.
We keep the same functionnalities as before.
> Extract page controller from carousel

- example/lib/main.dart
- example/lib/pages/section_page.dart
- example/lib/widgets/dummy_section.dart
- example/lib/widgets/row_list.dart
- lib/src/pages/rows/yaru_extra_option_row.dart
- lib/src/pages/rows/yaru_row.dart
- lib/src/pages/rows/yaru_single_info_row.dart
- lib/src/pages/rows/yaru_slider_row.dart
- lib/src/pages/rows/yaru_switch_row.dart
- lib/src/pages/rows/yaru_toggle_buttons_row.dart
- test/pages/rows/yaru_row_test.dart
Before:
```
_________ __________________ __________
|         |                  |          |
|         | trailing         |          |
| leading |                  | action   |
|         | description      |          |
|_________|__________________|__________|
```
After:
```
_________ __________________ __________
|         |                  |          |
|         | title            |          |
| leading |                  | trailing |
|         | subtitle         |          |
|_________|__________________|__________|
```
> YaruRow: rename child properties to match ListTile

- lib/src/pages/rows/yaru_extra_option_row.dart
- lib/src/pages/rows/yaru_row.dart
- lib/src/pages/rows/yaru_single_info_row.dart
- lib/src/pages/rows/yaru_slider_row.dart
- lib/src/pages/rows/yaru_switch_row.dart
- lib/src/pages/rows/yaru_toggle_buttons_row.dart
ListTile doesn't have such property either. In the settings app, there are only a handful of cases where the width property is used. Often it can be set for the entire section/column/list instead of each individual tile.
> Yaru*Row: remove the width property

- lib/src/pages/layouts/yaru_master_detail_page.dart
Technically, you could even rebuild the page if you wanted:
```dart
YaruMasterDetailPage(
initialIndex: _idx,
onSelected: (index) => setState(() => _idx = index),
)
```
Even though the real motivation is to be able to specify a page on startup _and_ that this might open up the possibility to allow full tile builders (#243).
> YaruMasterDetailPage: allow managing the page index

- lib/src/pages/layouts/yaru_portrait_layout.dart
Let apps decide where they want to put the back button if they are not using an app bar.
> YaruPortraitLayout: remove the FAB

- lib/src/pages/layouts/yaru_portrait_layout.dart
`SizedBox.expand()` expands to as large as the parent allows without needing to look up the window size.
> YaruPortraitLayout: expand pages to available size

- example/lib/pages/round_toggle_button_page.dart
|---|---|
| ![Screenshot from 2022-10-09 17-55-01](https://user-images.githubusercontent.com/140617/194766846-f105c2e6-6121-4167-b875-4e27ff0adfea.png) | ![Screenshot from 2022-10-09 17-54-55](https://user-images.githubusercontent.com/140617/194766853-0c8194ee-84ad-419c-aeaa-b2bf356857c8.png) |
Fixes: #257
> Example: center the toggle button to avoid stretching it

- example/lib/main.dart
- lib/src/pages/layouts/yaru_landscape_layout.dart
- lib/src/pages/layouts/yaru_master_detail_page.dart
- lib/src/pages/layouts/yaru_master_tile.dart
- lib/src/pages/layouts/yaru_page_item_list_view.dart
- lib/src/pages/layouts/yaru_portrait_layout.dart
- lib/yaru_widgets.dart
This gives full control over master-detail tiles. Notice that `YaruMasterTile` can be wrapped with any other widget such as `Tooltip` or `Semantics`.
```dart
YaruMasterDetailPage(
iconBuilder: (context, index, selected) => const Icon(Icons.foo),
titleBuilder: (context, index, selected) => const Text('Title'),
)
```
```dart
YaruMasterDetailPage(
tileBuilder: (context, index, selected) => YaruMasterTile(
leading: const Icon(Icons.foo),
title: const Text('Custom'),
subtitle: const Text('Lorem ipsum...'),
trailing: const Chip(label: Text('123'),
onTap: () {},
),
)
```
Ref: #255
> YaruMasterDetailPage: add tile builder

- example/lib/main.dart
- lib/src/controls/yaru_back_button.dart
- lib/src/pages/layouts/yaru_master_detail_page.dart
- lib/src/pages/layouts/yaru_portrait_layout.dart
- lib/yaru_widgets.dart
- pubspec.yaml
This is a pre-requisite for the master-detail app bar removal (#255), also discussed in ubuntu-flutter-community/software#354.
P.S. Proposing `YaruBackButton` instead of `YaruIconButton.back` because the former is easier to discover :slightly_smiling_face:
**NOTE**: rectangular vs. circular shape change and a dependency to **yaru_icons** - are these acceptable?
| Before | ~~After~~ | After
|---|---|---|
| ![Screenshot from 2022-10-10 11-45-08](https://user-images.githubusercontent.com/140617/194839092-fa9a1dc9-338f-494b-9ac4-24673e368104.png) | ![Screenshot from 2022-10-10 11-44-55](https://user-images.githubusercontent.com/140617/194839102-a66079e0-c98d-4aef-86ba-9794c76909f4.png) | ![Screenshot from 2022-10-10 11-45-08](https://user-images.githubusercontent.com/140617/194844697-7fc4ab4d- …
> Add YaruBackButton

- lib/src/pages/layouts/yaru_landscape_layout.dart
- lib/src/pages/layouts/yaru_master_detail_page.dart
- lib/src/pages/layouts/yaru_master_detail_theme.dart
- lib/src/pages/layouts/yaru_master_tile.dart
- lib/src/pages/layouts/yaru_page_item_list_view.dart
- lib/src/pages/layouts/yaru_portrait_layout.dart
- lib/yaru_widgets.dart
This PR implements the last item on the wish-list in #255 to give control over the internal values used for spacing, padding etc.
```dart
YaruMasterDetailTheme(
data: YaruMasterDetailThemeData(
breakpoint: 480,
tileSpacing: 4,
listPadding: EdgeInsets.only(top: 12, bottom: 34),
// ...
),
child: YaruMasterDetailPage(
// ..
),
),
```
> Yaru master detail theme

- lib/src/pages/layouts/yaru_landscape_layout.dart
- lib/src/pages/layouts/yaru_master_list_view.dart
- lib/src/pages/layouts/yaru_portrait_layout.dart
```
YaruMasterDetailTheme
|__YaruMasterDetailPage
|__YaruMasterListView
|    |__YaruMasterTile
|__YaruDetailPage
```
No visual changes. Just renaming an internal class to match the naming scheme of the rest.
> Rename YaruPageItemListView to YaruMasterListView

- lib/src/pages/layouts/yaru_compact_layout.dart
The navigation rail is in a Row that has its cross-axis alignment set to "stretch". Thus, all items in the row are vertically stretched to cover the entire height. A sized box that requests the whole window height is not necessary nor technically correct. :)
No visual changes.
> YaruCompactLayout: remove superfluous sized box

- lib/src/pages/layouts/yaru_master_list_view.dart
Don't create a new scroll controller every time the widget is rebuilt.
> YaruMasterListView: create only one scroll controller

- lib/src/pages/layouts/yaru_master_tile.dart
We have page animation, so the selected/unselected background change looks a bit rough without animation now imo.
**Before:**
https://user-images.githubusercontent.com/36476595/195073964-ac87bee8-8e24-4f4c-b2fc-c0bdd84a78cb.mp4
**After:**
https://user-images.githubusercontent.com/36476595/195073959-5e0d6d8a-2e5e-4c2c-90bf-aab940011ea0.mp4
> MaterDetails: add tiny selected tile background animation

- lib/src/pages/layouts/yaru_master_tile.dart
The subtitle color was overridden by setting a uniform `textColor` in `YaruMasterTile`'s `ListTile` - this commit restores the original look of `ListTile`
|-|-|-|
|Light| ![image](https://user-images.githubusercontent.com/113362648/195100756-09e0d8d6-daec-4b01-87b3-5d1f6d641080.png)  | ![image](https://user-images.githubusercontent.com/113362648/195101070-b52dbdfe-ed6e-4af1-bba4-d74a41e60570.png) |
|Dark| ![image](https://user-images.githubusercontent.com/113362648/195100631-6ea41ede-c99c-4b94-aa78-b07c60144159.png)  | ![image](https://user-images.githubusercontent.com/113362648/195100947-495b8b04-fa89-4a72-870b-ee8766c5732f.png) |
> set separate color for subtitle in YaruMasterTile

- lib/src/pages/layouts/yaru_landscape_layout.dart
Use DividerTheme instead of hardcoded color to be aligned with the compact layout.
No visual change.
> YaruLandscapeLayout: use DividerTheme

- example/lib/main.dart
- lib/src/pages/layouts/yaru_compact_layout.dart
- lib/src/pages/layouts/yaru_navigation_rail.dart
- lib/src/pages/layouts/yaru_navigation_rail_item.dart
- lib/yaru_widgets.dart
And expose YaruNavigationRailItem as the recommended default building block. This is essentially the same as #252 for YaruMasterDetailPage.
```dart
YaruCompactLayout(
length: 5,
iconBuilder: (context, index, selected) => Icon(...),
titleBuilder: (context, index, selected) => Text(...),
pageBuilder: (context, index) => ...
style: width > 620 ... : ...
)
```
```dart
YaruCompactLayout(
length: 5,
itemBuilder: (context, index, selected) => YaruNavigationRailItem(
icon: Icon(...),
label: Text(...)
style: width > 620 ... : ...
),
pageBuilder: (context, index) => ...
)
```
> YaruCompactLayout: replace icon/titleBuilder with itemBuilder

- lib/src/pages/yaru_tabbed_page.dart
We can now set the `splashBorderRadius` :tada: 
But the font size changed, it was because we was using a theme which wasn't extend the one from `context` (my fault).
If we want to keep the same look, I suppose we should fix this in `yaru.dart`?
**Before:**
https://user-images.githubusercontent.com/36476595/195403276-137d830e-a014-461b-8df2-3ff3b62e6c73.mp4
**After:**
https://user-images.githubusercontent.com/36476595/195403312-b9c0ff45-e223-447b-b24c-f9aae7a08284.mp4
https://user-images.githubusercontent.com/36476595/195403323-c0227ae4-fc3e-4d1a-a1bd-f9896a395f60.mp4
Fixes #50
> Re-add tab background

- example/lib/example_page_items.dart
- example/lib/pages/check_button_page.dart
- example/lib/pages/radio_button_page.dart
- lib/src/controls/yaru_check_button.dart
- lib/src/controls/yaru_radio_button.dart
- lib/src/controls/yaru_toggle_button.dart
- lib/src/controls/yaru_toggle_button_layout.dart
- lib/src/controls/yaru_toggle_button_theme.dart
- lib/yaru_widgets.dart
- test/controls/yaru_check_button_test.dart
- test/controls/yaru_radio_button_test.dart
- test/controls/yaru_toggle_button_test.dart
Minimal desktop-style check and radio buttons imported from [ubuntu-flutter-plugins/ubuntu_widgets](https://github.com/canonical/ubuntu-flutter-plugins/tree/main/packages/ubuntu_widgets).
| | Light | Dark |
|-|-|-|
| YaruCheckButton | ![image](https://user-images.githubusercontent.com/140617/195408182-e1fbff50-ca69-4ad3-b6eb-e5bf398e6fb6.png) | ![image](https://user-images.githubusercontent.com/140617/195408238-654d86dd-19cc-4d8b-a91a-ee24488c3384.png) |
| YaruRadioButton | ![image](https://user-images.githubusercontent.com/140617/195408833-df4a7b30-d81b-4e30-8427-6e5a9f96306d.png) | ![image](https://user-images.githubusercontent.com/140617/195408362-533819ab-1b25-43cd-943d-21796971f6b8.png) |
> Import CheckButton & RadioButton from ubuntu-flutter-plugins/ubuntu_widgets

- example/lib/pages/carousel_page.dart
- example/lib/pages/expandable_page.dart
- lib/src/utilities/yaru_carousel.dart
- lib/src/utilities/yaru_expandable.dart
**Before:**
**After:*
Fixes #288
> Replace all Material icons with Yaru ones

- example/lib/example_page_items.dart
- example/lib/main.dart
- lib/src/layouts/yaru_navigation_rail_item.dart
I let the tooltip message required, because in the configuration without label, it is the only way to understand what the item mean.
Related to previous PR: #243
> YaruNavigationRailItem: add tooltip

- lib/src/layouts/yaru_landscape_layout.dart
`DividerTheme.of(context).color` can be null (it is the case here), so I replaced it with `Theme.of(context).dividerColor`.
|-|-|-|
|Light| ![Capture d’écran du 2022-10-13 17-39-34](https://user-images.githubusercontent.com/36476595/195645604-fd6762fc-e6e3-4ba9-a469-e0ad9a22d11d.png) | ![Capture d’écran du 2022-10-13 17-40-45](https://user-images.githubusercontent.com/36476595/195645615-3d95297a-95a5-46c9-b2c6-6d0374f1e4e5.png) |
|Dark| ![Capture d’écran du 2022-10-13 17-41-04](https://user-images.githubusercontent.com/36476595/195645621-8af2aea0-a5b9-43bd-8d54-9ee40de78013.png) | ![Capture d’écran du 2022-10-13 17-41-21](https://user-images.githubusercontent.com/36476595/195645626-05793f06-22bc-4720-a796-59c4b2b0f81c.png) |
> LandscapeLayout: fix resize indicator color

- lib/src/controls/yaru_check_button.dart
- lib/src/controls/yaru_radio_button.dart
This PR exposes a few missing properties that general-purpose checks and radios must have.
> YaruCheckButton & YaruRadioButton: add missing behavioral properties

- example/lib/example_page_items.dart
- example/lib/pages/dialog_page.dart
- lib/src/constants.dart
- lib/src/controls/yaru_title_bar.dart
- lib/src/dialogs/yaru_dialog_title.dart
- lib/yaru_widgets.dart
Implement Yaru~~Dialog~~TitleBar with help of AppBar which already offers these building blocks.
|-|-|-|
|Light| ![image](https://user-images.githubusercontent.com/140617/195582563-ff9afab5-d5aa-4f8b-b58d-f3069f01dadf.png) | ![image](https://user-images.githubusercontent.com/140617/195583113-0b498119-7747-44ed-946c-13beb564dbc1.png) |
|Dark| ![image](https://user-images.githubusercontent.com/140617/195582515-5124bc57-2897-448f-baf7-d92065c0f2ee.png) | ![image](https://user-images.githubusercontent.com/140617/195583171-d5a34fb1-db01-4eae-a5ef-f7e9b6b03941.png) |
> Yaru~~Dialog~~TitleBar: add support for leading & trailing widgets

- example/lib/pages/banner_page.dart
- example/lib/pages/dialog_page.dart
- example/lib/pages/tabbed_page_page.dart
- lib/src/pages/yaru_tile.dart
- lib/src/utilities/yaru_banner.dart
YauBanner was yet one more static hodgepodge imported from a different project
Now it should be a bit more flexible.
Also it is now possible to add a third line (potentially important for the software app)
The watermark can now also be replaced by a different Widget if wanted.
I changed the example to show what is possible with the banner.
Fixes #306
|-|-|-|
|Light|![grafik](https://user-images.githubusercontent.com/15329494/196405155-6a3b05c1-f47b-4226-9558-cf7657d05d6e.png)|![grafik](https://user-images.githubusercontent.com/15329494/196410327-91924265-244a-4467-8182-191395cc03a7.png)|
|Dark|![grafik](https://user-images.githubusercontent.com/15329494/196405250-7e86312a-d4e5-4745-9924-0c40f7a0e458.png)|![grafik](https://user-images.githubusercontent.com/15329494/19641021 …
> Improve YaruBanner

- example/lib/example_page_items.dart
- example/lib/pages/popup_page.dart
- lib/src/controls/yaru_popup_menu_button.dart
- lib/yaru_widgets.dart
> Add YaruPopupMenuButton

- example/lib/pages/popup_page.dart
- lib/src/controls/yaru_popup_menu_button.dart
|-|-|-|
|Light|![image](https://user-images.githubusercontent.com/15329494/197112166-ba86e9b8-676a-4164-a848-d2caaf5f1d80.png)|![image](https://user-images.githubusercontent.com/15329494/197112083-8346e620-1ef0-4c3e-bada-1022bdd88838.png)|
|Dark|![image](https://user-images.githubusercontent.com/15329494/197112251-10330986-95b7-40b8-8b36-19c3c1fa60b2.png) |![image](https://user-images.githubusercontent.com/15329494/197112029-15af9fd0-1dfb-4c4a-8f72-549605db34bb.png)|
@jpnurmi as requested the decoration is private and the builder is now the parameter instead of the item list
I also tried to get closer to the outlined button.
> YaruPopupMenuButton: use builder and improve

- lib/src/constants.dart
- lib/src/controls/yaru_title_bar.dart
|---|---|
| ![image](https://user-images.githubusercontent.com/140617/197382098-42065a8b-a770-40c0-9b1f-a3b1fa36890a.png) | ![image](https://user-images.githubusercontent.com/140617/197382064-9ba93c14-8e2a-4321-9982-4e94ed342688.png) |
> Document and clean up the constants

- example/pubspec.yaml
- pubspec.yaml
^0.4.x automatically includes 0.4.3 but forcing 0.4.3+ ensures that YaruMasterDetailPage golden tests (#327) will pass for everyone locally.
> Upgrade yaru.dart to v0.4.3

- example/lib/example_page_items.dart
- example/pubspec.yaml
- update to yaru_icons 0.2.6
- use new switch icon
- use filled icons when available (checkbox and radio)
> Example: update nav icons

- example/lib/pages/carousel_page.dart
- lib/src/utilities/yaru_carousel.dart
For simpler use cases where the user doesn't need to control the carousel, it's more convenient if `YaruCarousel` internally creates its own controller on demand. It's important to keep in mind that `YaruCarousel` does not own `widget.controller` - only the internal controller that was created if the user did not supply any (i.e. `widget.controller` is null).
> YaruCarousel: allow creating without controller

- README.md
> README.md: remove old Yaru*Row and YaruPage references

- example/lib/pages/color_disk_page.dart
> Showcase all YaruValues of the enum instead of the hard-coded list.

- lib/src/constants.dart
- lib/src/controls/yaru_close_button.dart
Fixes #356
|-|-|-|
|Light| ![Capture d’écran du 2022-11-02 19-20-41](https://user-images.githubusercontent.com/36476595/199571203-3ac3b08c-33dc-4243-9efc-040b94756192.png) | ![Capture d’écran du 2022-11-02 19-21-25](https://user-images.githubusercontent.com/36476595/199571186-8fe2fee7-d5c7-4388-9f79-9598f652973e.png) |
|Dark| ![Capture d’écran du 2022-11-02 19-20-54](https://user-images.githubusercontent.com/36476595/199571196-8f403db5-8cb5-43f6-81eb-3f56eb0385de.png) | ![Capture d’écran du 2022-11-02 19-21-15](https://user-images.githubusercontent.com/36476595/199571194-fb7b567c-b40a-4d83-944f-0f1101e46efa.png) |
**Note:** Gtk headerbar is 48px height, but I needed to add 2 additional px cause of the titlebar bottom border to have the feeling it has the same height as …
> Decrease YaruTitleBar height

- lib/src/layouts/yaru_landscape_layout.dart
- lib/src/layouts/yaru_master_detail_page.dart
- lib/src/layouts/yaru_portrait_layout.dart
- test/pages/yaru_master_detail_page_test.dart
Adds a simple controller to `YaruMasterDetailPage` that allows to select the currently selected index.
> Master detail controller

- lib/src/utilities/yaru_carousel.dart
No visual changes.
Don't schedule a timer when no longer attached. This fixes the following exception that occurred while randomly browsing the example.
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 107 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
```
> Fix YaruCarouselController.startTimer()

- example/lib/pages/carousel_page.dart
- example/lib/pages/section_page.dart
- lib/src/pages/yaru_section.dart
Notice that according to the [box model](https://www.w3schools.com/css/css_boxmodel.asp), "margin" is outside the border while "padding" is inside. Now that we have `YaruBorderContainer`, we can use it internally and expose its margin, padding etc.
NOTE: The default (app-specific) 20px bottom-only margin was removed and needs to be taken into account when porting the settings app.
|-|-|-|
|Light| ![Screenshot from 2022-11-11 16-11-44](https://user-images.githubusercontent.com/140617/201368796-3fb630fa-2f92-4d32-9e86-6f10197f43a3.png) | ![Screenshot from 2022-11-11 16-10-36](https://user-images.githubusercontent.com/140617/201368698-9ca901f8-8070-4e4d-b0a2-7ca4b7346dcb.png) |
|Dark| ![Screenshot from 2022-11-11 16-11-48](https://user-images.githubusercontent.com/140617/2013 …
> YaruSection: sort out margin vs. padding etc.

- example/lib/pages/carousel_page.dart
- example/lib/pages/section_page.dart
- lib/src/pages/yaru_section.dart
It's easy enough to wrap stuff into a Row when needed, and then you'll have full control over the main & cross-axis alignment etc. ;-)
> YaruSection: simplify headline & remove headerWidget

- lib/src/layouts/yaru_landscape_layout.dart
> Fix: Desktop Web: separator of MD page is super white in the dark theme

- lib/src/controls/yaru_toggle_button_layout.dart
- test/controls/yaru_check_button_test.dart
- test/controls/yaru_radio_button_test.dart
- test/controls/yaru_switch_button_test.dart
- test/controls/yaru_toggle_button_test.dart
- test/yaru_golden_tester.dart
Don't expand the title and subtitle to infinite width (like ListTile does) but keep them at their intrinsic widths like check and radio buttons usually do on the desktop.
|---|---|
| ![Screenshot from 2022-11-23 22-06-45](https://user-images.githubusercontent.com/140617/203855393-0de98d9e-d758-4d21-ad9e-56f796c4c51c.png) | ![Screenshot from 2022-11-23 22-41-21](https://user-images.githubusercontent.com/140617/203855396-f5c30040-93f6-4e15-a050-5fd7ff2a57a0.png) |
> Toggle buttons: don't expand horizontally

- lib/src/pages/yaru_tile.dart
- lib/src/utilities/yaru_banner.dart
Similarly ListTileStyle, affects how YaruTile chooses title and subtitle text styles and paddings.
|-|-|-|
|Light| | |
|Dark| | |
> Introduce YaruTileStyle

- lib/src/utilities/yaru_banner.dart
The example with watermarks removed:
|---|---|
| ![image](https://user-images.githubusercontent.com/140617/204643439-3f692948-acd1-4a87-a940-a23d3180f906.png) | ![image](https://user-images.githubusercontent.com/140617/204643372-7dfd76df-9ddb-4a2e-b10a-0a0b92a0f7d8.png) |
> YaruBanner: don't ignore the surface tint color when no watermark is set

- lib/src/utilities/yaru_banner.dart
Use the same tint shade (elevation) regardless of whether a watermark is specified for consistent and predictable results.
[Screencast from 2022-11-29 21-58-03.webm](https://user-images.githubusercontent.com/140617/204646779-019b3637-32eb-411f-93b6-32b805430c59.webm)
[Screencast from 2022-11-29 21-58-41.webm](https://user-images.githubusercontent.com/140617/204646920-451eee55-b40c-47c6-b863-6962cae2d820.webm)
> YaruBanner: align tint/elevation with and without watermark

- example/lib/pages/banner_page.dart
- lib/src/utilities/yaru_banner.dart
There's one occurrence of `copyIconAsWatermark` in the `yaru_widgets.dart` example, and another in the software app. Both of them pass `watermarkIcon` so neither is actually "copying" the leading icon as a watermark. This PR is a proposal to make the API more intuitive and just check if `watermarkIcon != null`. One can pass the same widget to both properties if that's desired.
|-|-|-|
|Light| | |
|Dark| | |
> YaruBanner: remove effectively unused copyIconAsWatermark

- lib/src/layouts/yaru_compact_layout.dart
- lib/src/layouts/yaru_landscape_layout.dart
- lib/src/layouts/yaru_layout_index_controller.dart
- lib/src/layouts/yaru_master_detail_page.dart
- lib/src/layouts/yaru_page_controller.dart
- lib/src/layouts/yaru_portrait_layout.dart
- lib/yaru_widgets.dart
- test/pages/yaru_compact_layout_test.dart
- test/pages/yaru_master_detail_page_test.dart
WIP
Adds ~~`YaruLayoutIndexController`~~ `YaruPageController` that controls
|-|-|-|
|Light| | |
|Dark| | |
> Yaru layout index controller

- lib/src/utilities/yaru_banner.dart
The click mouse cursor is provided by the InkWell above the card.
|-|-|-|
|Light| | |
|Dark| | |
> YaruBanner: clean up unused internal mouse cursor property

- example/lib/pages/banner_page.dart
- lib/src/utilities/yaru_banner.dart
- lib/src/utilities/yaru_watermark.dart
- lib/yaru_widgets.dart
```dart
YaruBanner(
watermarkIcon: ...
...
),
```
```dart
YaruWatermark(
watermark: ...
child: YaruBannerOrAnythingElse(
...
),
),
```
> Extract YaruWatermark from YaruBanner

- lib/src/layouts/yaru_landscape_layout.dart
`YaruLandscapeLayout` is an internal helper class. It's not exported from `lib/yaru_widgets.dart`. Its sibling `YaruPortraitLayout` doesn't have docs either.
The docs are not only annoying to maintain but also cause confusion in code reviews. Having docs makes it look like a public class. The class gets easily mixed up with `YaruCompactLayout` with a similar name that on the other hand is a public class.
> YaruLandscapeLayout: remove docs from an internal helper class

- lib/src/utilities/yaru_banner.dart
Instead of letting `YaruTile` use its default 8px all-side padding and then passing an additional left-only 10px padding for the icon, pass 20px all-side padding to `YaruTile`. This eliminates the assumption that there's an icon and gives consistent paddings on all sides including in RTL mode.
|-|-|-|
|LTR| ![image](https://user-images.githubusercontent.com/140617/204774520-8efa8950-4779-4910-b43f-1148f98e952d.png) | ![image](https://user-images.githubusercontent.com/140617/204777025-8cc918b3-66d2-44b2-ab3c-e8c2753adcc8.png) |
|RTL| ![image](https://user-images.githubusercontent.com/140617/204774582-79223622-2c48-4d43-907c-ea417810ef7b.png) | ![image](https://user-images.githubusercontent.com/140617/204777077-79d366c5-4cc7-4ebc-9ef4-89258ba2a2a2.png) |
> YaruBanner: generalize padding & fix RTL

- lib/src/controls/yaru_checkbox.dart
- lib/src/controls/yaru_icon_button.dart
- lib/src/controls/yaru_option_button.dart
- lib/src/controls/yaru_popup_menu_button.dart
- lib/src/controls/yaru_radio.dart
- lib/src/controls/yaru_switch.dart
- lib/src/controls/yaru_togglable.dart
- lib/src/layouts/yaru_master_detail_theme.dart
- lib/src/pages/yaru_section.dart
- lib/src/pages/yaru_tabbed_page.dart
- lib/src/pages/yaru_tile.dart
- lib/src/utilities/yaru_banner.dart
- lib/src/utilities/yaru_border_container.dart
- lib/src/utilities/yaru_selectable_container.dart
- lib/src/utilities/yaru_watermark.dart
Make sure to use the text direction -agnostic `EdgeInsetsGeometry` instead of the LTR-specific `EdgeInsets` everywhere. This way, users can pass `EdgeInsetsDirectional` to support RTL where appropriate.
> Fix RTL support for paddings and margins

- lib/src/layouts/yaru_master_tile.dart
- lib/src/utilities/yaru_banner.dart
It's not an expensive call, but not free either. Every `Theme.of()` call implies a `Localizations.of()` call, so two inherited widget lookups both of which are basically hashmap lookups. Last but not least, the two are merged and cached, resulting in a third hashmap lookup. Therefore it's nice to store the theme data to a variable at the beginning of `build()` to avoid repeating the hashmap lookups several times.
```dart
static ThemeData of(BuildContext context) {
final _InheritedTheme? inheritedTheme = context.dependOnInheritedWidgetOfExactType<_InheritedTheme>(); // <== 1
final MaterialLocalizations? localizations = Localizations.of<MaterialLocalizations>(context, MaterialLocalizations); // <== 2
final ScriptCategory category = localizations?.scriptCategory ?? …
```
> Reduce repetitive Theme.of() calls

- lib/src/layouts/yaru_landscape_layout.dart
- lib/src/layouts/yaru_master_detail_page.dart
- lib/src/layouts/yaru_portrait_layout.dart
Allows inserting an arbitrary sticky item at the bottom of the master list, similar to the app bar at the top.
Close: #440
> Add MasterDetailPage.bottomBar

- lib/src/utilities/yaru_banner.dart
Expose the background color and the elevation to make it possible to control the composited background color + surface tint with elevation.
> YaruBanner: give full control over the colors

- lib/src/layouts/yaru_navigation_page.dart
- lib/src/layouts/yaru_navigation_rail.dart
This is `YaruNavigationPage`'s counterpart to `YaruMasterDetailPage.bottomBar` (#441) but behaviorally different. Unlike master-detail, navigation rail's leading and trailing widgets are inside the scroll view.
> Add YaruNavigationPage.leading/trailing

- lib/src/controls/yaru_title_bar.dart
This allows using YaruTitleBar as Scaffold.appBar.
```dart
Scaffold(
appBar: YaruTitleBar(),
body: ...
)
```
> The argument type 'YaruTitleBar' can't be assigned to the parameter type 'PreferredSizeWidget?' .dart([argument_type_not_assignable](https://dart.dev/diagnostics/argument_type_not_assignable))
https://api.flutter.dev/flutter/material/Scaffold/appBar.html
|-|-|-|
|Light| | |
|Dark| | |
> YaruTitleBar: implement PreferredSizeWidget

- lib/src/utilities/yaru_banner.dart
Fixes #448
|-|-|-|
|Light|![grafik](https://user-images.githubusercontent.com/15329494/205498895-c48ad728-d053-49d0-beeb-f5c60e6a692f.png)|![grafik](https://user-images.githubusercontent.com/15329494/205498895-c48ad728-d053-49d0-beeb-f5c60e6a692f.png)|
|Dark|![grafik](https://user-images.githubusercontent.com/15329494/205498944-7840f505-e4da-4b44-b50e-09a9ac1720df.png)| ![grafik](https://user-images.githubusercontent.com/15329494/205498868-518a478d-120a-458f-bc2e-e7b8f5c08b97.png)|
> YaruBanner: more sane default colors

- lib/src/layouts/yaru_master_detail_theme.dart
Implementing the [`ThemeExtension`](https://api.flutter.dev/flutter/material/ThemeExtension-class.html) interface for `YaruMasterDetailThemeData` makes it possible to use it in `(Yaru)ThemeData.extensions`.
```dart
YaruTheme(
data: const YaruThemeData(
extensions: [
YaruMasterDetailThemeData(
...
)
],
),
builder: (context, yaru, child) {
return MaterialApp(
theme: yaru.theme,
darkTheme: yaru.darkTheme,
home: Example.create(context),
);
},
)
```
> YaruMasterDetailThemeData: implement ThemeExtension interface

- lib/src/layouts/yaru_landscape_layout.dart
This ensures that snackbars and banners are shown on the detail page.
|---|---|
| ![image](https://user-images.githubusercontent.com/140617/210116044-47be313e-899d-4b5b-a34c-bd977477224b.png) | ![image](https://user-images.githubusercontent.com/140617/210116063-0399e0ed-4fa9-4dd9-8782-cfb0551e7e09.png) |
Fixes: #447
> MD: wrap detail page with ScaffoldMessenger in landscape layout

- lib/src/controls/yaru_title_bar.dart
- lib/src/controls/yaru_title_bar_theme.dart
- lib/yaru_widgets.dart
Visual changes extracted from #455, leaving out any actual top-level window-related functionality i.e. `YaruWindowTitleBar`, `YaruDialogTitleBar`, and `YaruWindowController`.
NOTE: This is a breaking change. `YaruTitleBar` no longer creates a `YaruCloseButton` that calls `Navigator.pop`. Instead, it has a set of properties that can be used to manage which `YaruWindowControls` to create.
P.S. `YaruWindowTitleBar` and `YaruDialogTitleBar` are still coming but without `window_manager` dependency as originally proposed in #455. :)
> YaruTitleBar: make themable and use window controls

- lib/src/controls/yaru_title_bar.dart
Use `FutureOr<void>` to allow passing either sync or async callbacks and rename `onMove` to `onDrag` to reduce ambiguity.
> YaruTitleBar: adjust callbacks

- lib/src/layouts/yaru_landscape_layout.dart
- lib/src/layouts/yaru_master_detail_page.dart
- lib/src/layouts/yaru_portrait_layout.dart
- test/pages/yaru_master_detail_page_test.dart
`MasterDetailPage` can be rebuilt with either a) a different `controller`, or b) a different `length` and `initialIndex`. Make sure `didUpdateWidget` checks for both cases.
Ref: ubuntu-flutter-community/settings#421
> MD: fix page controller updates

- lib/src/layouts/yaru_landscape_layout.dart
- lib/src/layouts/yaru_navigation_page.dart
Clears the navigator stack of the right pane in `YaruLandScapeLayout` and `YaruNavigationPage` when (re-)selecting an entry in the left pane.
See https://github.com/ubuntu-flutter-community/software/issues/254
Edit: This requires us to use the navigator provided by the respective Yaru page, rather than nesting another one below.
|-|-|-|
|Light| | |
|Dark| | |
> Navigation/MD pages: pop all but first on select

- .github/workflows/build.yml
Build jobs have started failing with errors like:
```
Fetched 11.0 MB in 7s (1537 kB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_22.0.5-0ubuntu0.1_amd64.deb  404  Not Found [IP: 40.119.46.219 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libegl1-mesa-dev_22.0.5-0ubuntu0.1_amd64.deb  404  Not Found [IP: 40.119.46.219 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.
```
- https://github.com/ubuntu/yaru_widgets.dart/actions/runs/3891996009/jobs/6643045813
- https://github.com/ubuntu/yaru_widgets.dart/actions/runs/3891936309/jobs/6643042784
- https://github.com/ubuntu/yaru_widgets.dart/actions/runs/3892061928/jobs/6643034087
- …
> CI: add missing apt update

- example/lib/example_page_items.dart
I added a lot of new filled icons in yaru_icons, so let's use them in the navigation :)
https://user-images.githubusercontent.com/36476595/211783903-4bf45893-7a53-423a-877c-9eb722e20ab7.mp4
> Use new filled icons in sidebar navigation

- lib/src/controls/yaru_togglable.dart
- Center the painter to fix the stretch effect ;
- Add `RepaintBoundary` widget around the painter to keep a sharp look ;
- Correct weird logic of putting a `Padding` in a `SizedBox`, which was require to add up padding value to the dimensions.
@jpnurmi as you can see, I'm now using a personal fork ;)
**Before:**
**After:**
Fixes #484
> Fix stretched yaru togglables

- lib/src/constants.dart
- lib/src/controls/yaru_togglable.dart
@Jupi007 is this ok to hide? do we need it in the public `constants.dart`? it's only used in `togglable.dart`.
Ref: #489
> Hide `kTogglableActiveResizeFactor` out of the public API

- lib/src/constants.dart
- lib/src/controls/yaru_checkbox.dart
- lib/src/controls/yaru_radio.dart
@Jupi007 What about this? I left it to a separate PR because this could be controversial...
Ref: #489
> Move `kCheckboxRadio*` constants out of the public API

- CHANGELOG.md
- pubspec.yaml
* MD: wrap detail page with ScaffoldMessenger in landscape layout by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/463
* Add YaruNavigationPageTheme.railPadding by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/466
* YaruTitleBar: make themable and use window controls by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/464
* YaruTitleBar: adjust callbacks by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/467
* MD: fix page controller updates by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/468
* NavigationPage: fix controller updates by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/469
* Update goldens for yaru.dart border changes by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/472
* …
> Release 2.0.0-beta-4

- lib/src/utilities/yaru_expandable.dart
> YaruExpandable: expand button position control

- example/lib/code_snippet_button.dart
- example/lib/example.dart
- example/lib/example_page_items.dart
By default, the same title string is used for building the basic Text title for pages, used as a tooltip message, and code snippet dialog title. Custom title builders are still supported for more advanced scenarios.
> Example: eliminate duplicate page titles/tooltips

- lib/src/layouts/yaru_detail_page.dart
Use the height of the app/title bar that is passed in instead of forcing `AppBarTheme.toolbarHeight` which does currently not match with `kYaruTitleBarHeight`. Perhaps they should, though?
|---|---|
| ![image](https://user-images.githubusercontent.com/140617/212022296-8621454c-a8f8-4343-b3c4-3f98e6e5944a.png) | ![Screenshot from 2023-01-12 09-52-20](https://user-images.githubusercontent.com/140617/212022049-d83998ed-3c72-467a-9310-0173f126e1bc.png) |
> YaruDetailPage: fix app/title bar height

- lib/src/controls/yaru_title_bar.dart
- lib/src/controls/yaru_window.dart
- test/controls/yaru_title_bar_test.dart
This fixes a regression introduced by #506 that e.g. the settings dialog title bar in the example is not draggable.
> YaruWindowTitleBar: fix state init

- lib/src/controls/yaru_title_bar.dart
This makes it possible to use `YaruTitleBar` in a `YaruDetailPage` that uses a unique hero tag to keep the whole app/title bar in place during page transitions. The inner title bar cannot contain another hero tag because heroes must not be nested.
Close: #503
> YaruTitleBar: fix hero conflict

- lib/src/controls/yaru_title_bar.dart
- lib/src/controls/yaru_title_bar_theme.dart
This allows creating "placeholder" title bars without any buttons but with full functionality i.e. double- and right-click handling.
```dart
appBar: const YaruWindowTitleBar(
title: Text('Example'),
style: YaruTitleBarStyle.background,
)
```
Fixes: #508
> Add YaruTitleBarStyle (hidden, background, normal)

- lib/src/layouts/yaru_landscape_layout.dart
- lib/src/layouts/yaru_portrait_layout.dart
This makes sure that the left-side title bar automatically switches between "normal" and "undecorated" styles.
[Screencast from 2023-01-13 08-15-45.webm](https://user-images.githubusercontent.com/140617/212260185-47ecf179-9cf6-4541-82ed-3e8540b88332.webm)
> MD: specify the desired title bar style in landscape and portrait modes

- lib/src/controls/yaru_title_bar.dart
- lib/src/layouts/yaru_portrait_layout.dart
Now that we have the "undecorated" style, we can use that on web so YaruWindowTitleBar becomes a drop-in replacement for AppBar.
> YaruWindowTitleBar: improve defaults for web

- lib/src/controls/yaru_title_bar.dart
To make `YaruTitleBar` closer to a drop-in replacement of `AppBar`.
Close: #515
> YaruTitleBar: trailing -> actions

- example/lib/code_snippet_button.dart
- example/lib/example.dart
It takes too much space when we switch to a window title bar. How about using a FAB instead?
|---|---|
| ![image](https://user-images.githubusercontent.com/140617/212483338-a545dd09-5a3a-4e3f-baa2-d6136195a433.png) | ![Screenshot from 2023-01-14 17-25-26](https://user-images.githubusercontent.com/140617/212483282-e2098d9d-3d47-43a1-b155-27bba715ca5d.png) |
> Example: move code snippet button out of the app bar

- lib/src/controls/yaru_togglable.dart
- lib/src/controls/yaru_window_control.dart
This PR removes all RepaintBoundary widgets, which can cause performance issue.
The only side effect is that window controls and togglable widgets will no more be aligned on physical display. It will result in blurred widgets in some situations, like inside alignment widgets.
I taken an attentive look, and all material widgets got the same behavior of blurred look.
Side by side, material and yaru checkboxes:
[Capture vidéo du 2023-01-14 17-39-38.webm](https://user-images.githubusercontent.com/36476595/212485708-e4c80e80-9710-4ce7-ac2d-bb6193528edf.webm)
Fixes #492
> Remove all RepaintBoundary widgets

- example/lib/example.dart
- example/lib/example_page_items.dart
- example/lib/main.dart
- example/lib/pages/navigation_page.dart
> Example: make better use of YaruWindowTitleBar

- lib/src/controls/yaru_title_bar.dart
- lib/src/controls/yaru_title_bar_gesture_detector.dart
The problem was that `GestureDetector.onDoubleTap` creates an "eager" double-tap recognizer that forces a 300ms delay for any (single-)tap recognizer in the gesture arena.
This PR drops `GestureDetector` in favor of `RawGestureDetector` that allows using custom gesture recognizers, and implements a "passive" double-tap recognizer that is just an extended (single-)tap recognizer but detects double-taps from incoming (single-)taps. It keeps a history of the previous tap and compares the duration and distance with help of the constants defined in `flutter/gestures.dart`.
Fixes: #516
> YaruTitleBar: fix single-click delay

- lib/src/layouts/yaru_master_detail_page.dart
Adds a scaffold to fix indefinite issues with flutter showing the root GTK window and therefore not applying the correct theme. This is a regression from main.
maybe fixes #522 
|-|-|-|
|Light|![Screenshot from 2023-01-15 01-55-09](https://user-images.githubusercontent.com/73116038/212513972-bb997948-e7e9-403b-ad80-c81456c87258.png)|![Screenshot from 2023-01-15 01-56-40](https://user-images.githubusercontent.com/73116038/212514146-35469ac3-85c4-49bf-9de0-283c6801dccb.png)  |
|Dark|   ![Screenshot from 2023-01-15 01-58-47](https://user-images.githubusercontent.com/73116038/212 …
> Add scaffold to yaru-master-detail page

- lib/src/controls/yaru_checkbox.dart
- lib/src/controls/yaru_radio.dart
- lib/src/controls/yaru_switch.dart
- lib/src/controls/yaru_togglable.dart
For example:
This is the part one of yaru togglable theming.
In a second time, maybe introduce some kind of app global theming? Wdyt @jpnurmi @Feichtmeier ?
Fixes #526
> Allow color customization of single togglable

- lib/src/layouts/yaru_landscape_layout.dart
since yaru master details now has a scaffold we dont need this anymore
|-|-|-|
|Light| | |
|Dark| | |
> Landscape: remove separator fix for web, not needed anymore

- lib/src/pages/yaru_tile.dart
I noticed in canonical/ubuntu-desktop-installer#1316 that YaruTile didn't allow me to pass a nullable title even though [ListTile](https://api.flutter.dev/flutter/material/ListTile-class.html) does allow it.
> YaruTile: make title optional

- lib/src/controls/yaru_title_bar.dart
When AppBarTheme.titleTextStyle is null.
Close: #518
> YaruTitleBar: use TextTheme.titleLarge as a fallback

- lib/src/layouts/yaru_navigation_page.dart
With quick and dirty changes to the example just to illustrate how it keeps the title bar in place during page transitions.
[Screencast from 2023-01-19 14-57-04.webm](https://user-images.githubusercontent.com/140617/213461424-8436d578-a369-49a0-99fc-d1292b8c30d5.webm)
[Screencast from 2023-01-19 14-57-17.webm](https://user-images.githubusercontent.com/140617/213461466-ddc1a4b5-1023-4a77-a38e-4621a4fc7ba5.webm)
> YaruNavigationPage: add HeroController to support YaruDetailPage

- example/lib/code_snippet_button.dart
- lib/src/pages/yaru_tile.dart
```
Flutter 3.7.0-1.4.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 686fe913dc (9 days ago) • 2023-01-10 16:14:01 -0800
Engine • revision ac5c83dd5f
Tools • Dart 2.19.0 (build 2.19.0-444.4.beta) • DevTools 2.20.0
```
> Fix use of deprecated members (beta channel)

- example/lib/example.dart
M3 bottom bar has gained default padding and a height of 80px on the beta channel. We can switch to a simpler structure to avoid having to customize it in the example. All we need is a tile with an opaque background and a little padding around. :)
| | Before | After |
|---|---|---|
| Stable | ![image](https://user-images.githubusercontent.com/140617/213649558-9574ec3b-119d-44c4-8f95-79229037f1bb.png) | ![image](https://user-images.githubusercontent.com/140617/213649287-28249220-21b7-4a83-bc8b-bbff7244c962.png) |
| Beta | ![image](https://user-images.githubusercontent.com/140617/213649643-9b778349-1e81-4586-abad-06cd95f55b10.png) | ![image](https://user-images.githubusercontent.com/140617/213649724-5e32bf39-55e3-4792-929f-f9f9d9dc1204.png) |
NOTE: The white divider is a separate issue …
> Example: fix the settings bottom bar look sensible with Flutter beta

- lib/src/layouts/yaru_detail_page.dart
No visual changes. A partial fix to #549. Something similar for YaruTitleBar comes separately.
> YaruDetailPage: allow specifying the hero tag

- lib/src/controls/yaru_title_bar.dart
The YaruTitleBar counterpart of #553.
Close: #549
> YaruTitleBar: allow specifying the hero tag

- CHANGELOG.md
- pubspec.yaml
* Landscape: remove separator fix for web, not needed anymore by @Feichtmeier in https://github.com/ubuntu/yaru_widgets.dart/pull/529
* Remove YaruTabbedPage by @Feichtmeier in https://github.com/ubuntu/yaru_widgets.dart/pull/530
* YaruTile: make title optional by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/533
* YaruTitleBar: use TextTheme.titleLarge as a fallback by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/535
* Revert "Remove all RepaintBoundary widgets" by @Jupi007 in https://github.com/ubuntu/yaru_widgets.dart/pull/537
* Update goldens by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/538
* YaruPopupMenuButton: sync border with OutlinedButton by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/539
* YaruPopupMenuButton: …
> Release 2.0.0-beta-5

- lib/src/controls/yaru_title_bar.dart
- lib/src/controls/yaru_window.dart
Currently, `WindowManager` offers no way to listen to changes in whether a window is minimizable/maximizable/closable (leanflutter/window_manager#287).
This PR adds a hidden way for applications to notify that the title bar should update itself as required for canonical/ubuntu-desktop-installer#1329.
> YaruWindowTitleBar: allow notifying window state changes

- lib/src/controls/yaru_title_bar.dart
- lib/src/controls/yaru_window.dart
- lib/yaru_widgets.dart
This allows apps to set the window title, and the relevant window attributes (minimizable, maximizable, closable) in a way that doesn't need the recently added [updateState()](https://github.com/ubuntu/yaru_widgets.dart/pull/561) workaround.
Before:
```dart
windowManager.setClosable(false);
YaruWindow.of(context).updateState(); // or YaruWindow.updateState(context);
```
After:
```dart
YaruWindow.of(context).setClosable(false); // or YaruWindow.setClosable(context, false);
```
> Expose YaruWindow API

- lib/src/layouts/yaru_navigation_page_theme.dart
I tried generating the docs out of curiosity and one class stood out...
> Fix YaruNavigationPageThemeData class name

- lib/src/controls/yaru_title_bar.dart
- pubspec.yaml
TextFieldTapRegion was introduced in Flutter 3.7.0 to solve the problem that clicking anywhere outside a TextField would reset input focus.
[Screencast from 2023-01-26 22-09-34.webm](https://user-images.githubusercontent.com/140617/214951225-0a6e6b31-6335-4426-a670-86e7a0dacdc0.webm)
[Screencast from 2023-01-26 22-07-55.webm](https://user-images.githubusercontent.com/140617/214951249-61fe399a-7139-477e-b4d8-69c0fc058093.webm)
Fixes: #550
> Prevent YaruTitleBar from reseting input focus

- lib/src/layouts/yaru_navigation_rail_item.dart
The current way of control a navigation page pane width weird because it is done by tiles themself.
For now I added a way to control this width, I'll think about something to control this size from the navigation page itself, without introduce breaking change later (in any case these changes are needed).
Related to #570
> Allow YaruNavigationRailItem width control

- lib/src/controls/yaru_switch.dart
- lib/src/controls/yaru_togglable.dart
- The drag zone is located in the dot region ;
- I exposed important private properties and method of the abstract `YaruTogglableState` class, so descendent classes can access to them ;
- The `MouseRegion` is removed with a disabled switch.
[Capture vidéo du 2023-01-28 17-22-43.webm](https://user-images.githubusercontent.com/36476595/215277684-26d72f52-f60d-4823-9930-5405af900cfc.webm)
Fixes #405
> Allow switch dot to be mouse dragged

- example/lib/example_page_items.dart
- example/lib/pages/clip_page.dart
- lib/foundation.dart
- lib/src/foundation/yaru_clip.dart
Convenient for creating app previews and theme cards etc.
Ref: #580
> Introduce YaruClip.diagonal()

- lib/src/widgets/navi_rail/yaru_navigation_rail_item.dart
Allow null `YaruNavigationRailItem` label with compact style.
> Allow null YaruNavigationRailItem label with compact style

- lib/src/widgets/yaru_banner.dart
YaruBanner is cool with its hover and focus highlights and press effects etc. but I've often missed the ability to mark it as selected to be able to use it as a selection card.
| Light | Dark |
|---|---|
| ![image](https://user-images.githubusercontent.com/140617/216840603-a07ec5fd-da87-4d13-8add-2bad3fe6a72b.png) | ![Screenshot from 2023-02-05 20-19-17](https://user-images.githubusercontent.com/140617/216840225-6c650d85-d0f5-4dbe-8fac-92a2d1c5da6c.png) |
> Add YaruBanner.selected property

- lib/src/widgets/yaru_title_bar.dart
Fixes: #577
|-|-|-|
|Light| ![Screenshot from 2023-02-05 22-57-46](https://user-images.githubusercontent.com/140617/216848361-88c42f7e-267a-4708-ba7d-79e39bbbb1cd.png) | ![Screenshot from 2023-02-05 22-57-29](https://user-images.githubusercontent.com/140617/216848366-c63bdd04-55b8-46b0-8ba5-2a442e007511.png) |
|Dark| ![Screenshot from 2023-02-05 22-56-45](https://user-images.githubusercontent.com/140617/216848378-217b62eb-90b8-4e95-bbd7-f050ede4b596.png) | ![Screenshot from 2023-02-05 22-57-11](https://user-images.githubusercontent.com/140617/216848373-e51b20ba-21a9-4565-b50f …
> YaruTitleBar: set an opaque background when the window is inactive

- lib/src/widgets/yaru_carousel.dart
- lib/src/widgets/yaru_page_indicator.dart
> Improve YaruCarousel comments

- lib/src/widgets/yaru_expandable.dart
- add `expandIconPadding` property ;
- fix missing comments and punctuation.
Fixes #604
> YaruExpandable: leave iconbutton padding indvidually from widget padding

- lib/src/widgets/yaru_carousel.dart
I don't know whyn but the `curve` parameter was passed to `nextPage` and `previousPage` methods.
> Pass curve parameter to next/previousPage methods

- pubspec.yaml
Probably a leftover from the app template. The package was generated without passing "--template package" so Flutter generated a pubspec for an app.
Fixes: #607
> pubspec.yaml: clean up `uses-material-design: true`

- CHANGELOG.md
- pubspec.yaml
* Add diagnosticable properties to togglable widgets by @Jupi007 in https://github.com/ubuntu/yaru_widgets.dart/pull/579
* YaruSection: fix unbounded height by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/584
* pubspec: add missing issue tracker link by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/590
* Restructure by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/586
* Update screenshot by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/589
* Introduce YaruClip.diagonal() by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/591
* Allow null YaruNavigationRailItem label with compact style by @Jupi007 in https://github.com/ubuntu/yaru_widgets.dart/pull/592
* Introduce YaruPageIndicator by @Jupi007 in …
> Release 2.0.2

- example/lib/pages/page_indicator.dart
- lib/src/widgets/yaru_page_indicator.dart
Allows to customize the size and spacing of `YaruPageIndicator`'s dots:
[Screencast from 2023-02-22 12-48-53.webm](https://user-images.githubusercontent.com/113362648/220611821-6b85ab12-973f-463e-bf70-383df1521b2e.webm)
Fix #622
|-|-|-|
|Light| | |
|Dark| | |
> YaruPageIndicator: add custom scale parameters

- lib/src/widgets/yaru_page_indicator.dart
- lib/src/widgets/yaru_page_indicator_theme.dart
I used a "decoration builder" because it allows to do special things like this:
https://user-images.githubusercontent.com/36476595/221298238-c784a71b-168b-4419-a654-15f4045629d1.mp4
Fixes #631
> Introduce YaruPageIndicatorTheme

- .github/PULL_REQUEST_TEMPLATE.md
Update the PR template for the new branch organization.
For reminder:
- now `main` is for the development of the new features ;
- a new `2.1.x` branch will be created after this PR being merged, based on `main`, for every bug fixes.
Then, I'll create a PR to cherry-pick the only commit from `2.2-dev` to `main`.
> Update PR template for the new branch organization

- lib/src/widgets/yaru_switch.dart
I had only pushed #633 into the `2.2-dev` branch, so I cherry-pick it to `main` which is the new dev branch.
I just created the `release` branch based on current main (stable so), after merging this PR `main` will become the dev branch.
> Cherry pick 2.2-dev into main

- lib/src/widgets/yaru_check_button.dart
- lib/src/widgets/yaru_checkbox.dart
- lib/src/widgets/yaru_checkbox_list_tile.dart
- lib/src/widgets/yaru_checkbox_theme.dart
- lib/src/widgets/yaru_radio.dart
- lib/src/widgets/yaru_radio_button.dart
- lib/src/widgets/yaru_radio_list_tile.dart
- lib/src/widgets/yaru_radio_theme.dart
- lib/src/widgets/yaru_switch.dart
- lib/src/widgets/yaru_switch_button.dart
- lib/src/widgets/yaru_switch_list_tile.dart
- lib/src/widgets/yaru_switch_theme.dart
- lib/src/widgets/yaru_togglable.dart
- lib/src/widgets/yaru_toggle_button.dart
- lib/src/widgets/yaru_toggle_button_theme.dart
- https://github.com/canonical/ubuntu-desktop-installer/issues/1532
> Check/Radio/Switch/Button/ListTile: allow customizing mouse cursor

- lib/src/widgets/master_detail/yaru_portrait_layout.dart
It should also have one, just like `YaruLandscapeLayout` and `YaruNavigationPage` do.
> `YaruPortraitLayout`: add missing hero controller

- lib/src/widgets/yaru_banner.dart
There's no visual change by default but this makes it possible to change the mouse cursor to anything, such as `SystemMouseCursors.basic`.
|---|---|
| ![image](https://user-images.githubusercontent.com/140617/222958463-7b3b1baa-d856-4504-b82b-1c4ef9d25487.png) | ![image](https://user-images.githubusercontent.com/140617/222958443-b0cd3d33-2ffb-4bc0-87b6-602f0ca4d3fc.png) |
> Add `YaruBanner.mouseCursor`

- lib/src/widgets/yaru_selectable_container.dart
There's no visual change by default but this makes it possible to change the mouse cursor to anything, such as `SystemMouseCursors.basic`.
|---|---|
| ![Screenshot from 2023-03-05 13-31-49](https://user-images.githubusercontent.com/140617/222960743-1fe2b941-6e6a-4d9e-b25e-030da69b186f.png) | ![image](https://user-images.githubusercontent.com/140617/222960725-e2847513-d60a-4d2a-969f-d2f9818162de.png) |
> Add YaruSelectableContainer.mouseCursor

- lib/widgets.dart
> widgets.dart: add missing export yaru_page_indicator_theme.dart

- lib/src/widgets/yaru_page_indicator.dart
- lib/src/widgets/yaru_page_indicator_theme.dart
There's no visual change by default but this makes it possible to change the mouse cursor to anything, such as `SystemMouseCursors.basic`.
|---|---|
| ![image](https://user-images.githubusercontent.com/140617/222961772-a206c618-86b1-4fe3-b353-10a47d6de351.png) | ![image](https://user-images.githubusercontent.com/140617/222961804-8698f5bd-dc71-4d19-bb77-478cfa48f68f.png) |
> Add YaruPageIndicator(ThemeData).mouseCursor

- lib/src/widgets/yaru_popup_menu_button.dart
There's no visual change by default but this makes it possible to change the mouse cursor to anything, such as `SystemMouseCursors.basic`.
> Add YaruPopupMenuButton.mouseCursor

- lib/src/widgets/yaru_color_disk.dart
Helps to give it an interactive feeling if the pointing finger mouse cursor is turned to a basic cursor for a more desktop'ish feeling.
[Screencast from 2023-03-05 16-36-50.webm](https://user-images.githubusercontent.com/140617/222970347-17336401-9994-400a-83d0-cefc66c7a6f3.webm)
> YaruColorDisk: add subtle hover & focus highlight

- lib/src/widgets/yaru_check_button.dart
- lib/src/widgets/yaru_page_indicator.dart
- lib/src/widgets/yaru_popup_menu_button.dart
- lib/src/widgets/yaru_radio_button.dart
- lib/src/widgets/yaru_switch_button.dart
- lib/src/widgets/yaru_toggle_button.dart
I was looking at some old Flutter PRs for themable mouse cursors and noticed that the `MouseCursor` type of widget properties were not used "as is" but also resolved against the widget state with help of `MaterialStateProperty.resolveAs`. The Flutter team recommended doing it this way to support `MaterialStateMouseCursor` in place of `MouseCursor`.
> Resolve mouse cursor widget properties

- lib/src/widgets/yaru_checkbox.dart
- lib/src/widgets/yaru_radio.dart
- lib/src/widgets/yaru_switch.dart
- lib/src/widgets/yaru_togglable.dart
Allows the surrounding `YaruToggleButton` to control the hovered state for its contained `YaruTogglable` when the label is hovered.
Inspired by Flutter's ButtonStyleButton, the base class of ElevatedButton, OutlinedButton, FilledButton, and TextButton:
https://api.flutter.dev/flutter/material/ButtonStyleButton/statesController.html
Ref: #659
> YaruTogglable: add states controller

- lib/src/widgets/yaru_check_button.dart
- lib/src/widgets/yaru_radio_button.dart
- lib/src/widgets/yaru_switch_button.dart
This is a noisy preparation step for #659 to make it possible for `YaruToggleButton` subclasses to create and dispose an internal `MaterialStatesController`.
> Make YaruToggleButton subclasses stateful

- lib/src/widgets/yaru_watermark.dart
Presumably, something called "watermark" is non-interactive and should therefore not block hover.
[Screencast from 2023-03-06 10-55-17.webm](https://user-images.githubusercontent.com/140617/223077234-a5b1a2b2-1a2d-4853-b10c-251c0cb9e7c4.webm)
[Screencast from 2023-03-06 10-55-33.webm](https://user-images.githubusercontent.com/140617/223077293-bf6b5215-588e-4fdc-8c19-b41fdff504b9.webm)
> YaruWatermark: ignore pointer for the watermark

- lib/src/widgets/yaru_check_button.dart
- lib/src/widgets/yaru_radio_button.dart
- lib/src/widgets/yaru_switch_button.dart
- lib/src/widgets/yaru_toggle_button.dart
Add a hover effect for the indicator when hovering over the label to highlight the interactive nature of the label.
This becomes more important if the web-oriented pointing finger mouse cursor is changed to a more desktop'ish "basic" mouse cursor.
[Screencast from 2023-03-06 11-09-53.webm](https://user-images.githubusercontent.com/140617/223081226-07a0d619-616e-4529-a499-5a81f06e7ba4.webm)
[Screencast from 2023-03-06 11-10-25.webm](https://user-images.githubusercontent.com/140617/223081282-35119503-67f1-4074-9841-13cc0613ccdb.webm)
[Screencast from 2023-03-06 11-10-38.webm](https://user-images.githubusercontent.com/140617/223081310-acd5f9bd-0ab1-4ba7-a037-5a293596b1d5.webm)
Close: #659
> YaruCheck/Radio/SwitchButton: add hover & press effects

- lib/src/widgets/master_detail/yaru_master_detail_page.dart
> Add `YaruMasterDetailPage.orientationOf()` and `appBarBuilder`

- example/lib/pages/page_indicator.dart
- lib/src/widgets/yaru_carousel.dart
- lib/src/widgets/yaru_page_indicator.dart
Restore the old `dotSize` & `dotSpacing` arguments for the default constructor, and introduce an alternative named constructor for the new item size builder and layout delegate. This would be enough to avoid breaking the installer that is already using `dotSize` & `dotSpacing`. WDYT?
> YaruPageIndicator: restore compatibility

- lib/src/widgets/yaru_autocomplete.dart
Flutter's [Autocomplete](https://api.flutter.dev/flutter/material/Autocomplete-class.html) widget expands the options popup to all available width. Given that it looks somehow unusual on desktop, we made it possible to override the width in https://github.com/ubuntu/yaru_widgets.dart/pull/668.
Most often, the autocomplete widget can be simply wrapped with a LayoutBuilder to get the width _but_ things get more complicated when trying to use it in a dialog because LayoutBuilder naturally doesn't support intrinsic sizes. Therefore, I'm proposing to make this the default behavior and let `YaruAutocomplete` calculate the matching width under the hood. The old behavior is still possible by e.g. passing the screen width or simply `optionsWidth: double.infinity`.
|---|---|
| …
> YaruAutocomplete: calculate matching options width by default

- example/lib/example.dart
- example/lib/example_page_items.dart
- example/lib/pages/autocomplete_page.dart
NOTE: The banner page is the default because the autocomplete page is not the most attractive page... :P
> Example: add autocomplete

- CHANGELOG.md
- pubspec.yaml
* YaruAutocomplete: calculate matching options width by default by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/673
* Example: add autocomplete by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/674
> Release 2.2.1

- example/lib/main.dart
- example/pubspec.yaml
- lib/src/widgets/master_detail/yaru_master_tile.dart
- lib/src/widgets/yaru_title_bar.dart
- lib/src/widgets/yaru_window_control.dart
- pubspec.yaml
Adds high contrast borders to
- `YaruTitleBar`
- `YaruWindowControl`
- `YaruMasterTile`
> Add support for high contrast theme

- lib/src/widgets/yaru_title_bar_theme.dart
The issue is not super well visible in the compressed recordings but basically, the title bar border disappears for a moment whenever the entire app is rebuilt due to language change, and the AnimatedTheme baked into MaterialApp kicks in.
[Screencast from 2023-03-30 13-19-49.webm](https://user-images.githubusercontent.com/140617/228820562-b4a557fe-775b-4e70-97c3-b36296702e0b.webm)
[Screencast from 2023-03-30 13-20-36.webm](https://user-images.githubusercontent.com/140617/228820610-be7f60c6-df9d-41e1-bfd5-e8a69b238928.webm)
> YaruTitleBarTheme: fix border side lerp

- analysis_options.yaml
- example/analysis_options.yaml
- example/lib/code_snippet_button.dart
- example/lib/pages/carousel_page.dart
- example/lib/pages/checkbox_page.dart
- example/lib/pages/expandable_page.dart
- example/lib/pages/icon_button_page.dart
- example/lib/pages/option_button_page.dart
- example/lib/pages/popup_page.dart
- example/lib/pages/radio_page.dart
- example/lib/pages/section_page.dart
- example/lib/pages/switch_page.dart
- example/pubspec.yaml
- lib/src/widgets/master_detail/yaru_landscape_layout.dart
- lib/src/widgets/master_detail/yaru_master_detail_page.dart
- lib/src/widgets/master_detail/yaru_portrait_layout.dart
- lib/src/widgets/yaru_circular_progress_indicator.dart
- lib/src/widgets/yaru_draggable.dart
- lib/src/widgets/yaru_expansion_panel_list.dart
- lib/src/widgets/yaru_linear_progress_indicator.dart
- pubspec.yaml
- test/widgets/yaru_popup_menu_button_test.dart
- test/widgets/yaru_popup_menu_item_test.dart
- test/yaru_golden_tester.dart
This PR upgrades the dependency of [`flutter_lints`](https://pub.dev/packages/flutter_lints) to its current major version.
The only breaking change was that it increased Dart SDK's constraints to `>=2.17.0`, but this package already has that requirement since 7e3bde7.
I've also removed two rules that were manually enabled, since the new version of [`lints`](https://pub.dev/packages/lints) (which `flutter_lints` depends on) already enables them. New linter warnings appear after upgrading, and I've fixed some of those with `dart fix --apply` and others manually.
I did the same for the `example` project.
> Upgrade to `flutter_lints` 2.0

- lib/src/widgets/master_detail/yaru_master_list_view.dart
Remove useless `YaruMasterListView.materialTiles` which is no longer used anywhere.
Closes #706
> Remove useless YaruMasterListView.materialTiles

- example/lib/example.dart
- lib/src/widgets/master_detail/yaru_landscape_layout.dart
- lib/src/widgets/master_detail/yaru_master_detail_page.dart
- lib/src/widgets/master_detail/yaru_master_list_view.dart
- lib/src/widgets/master_detail/yaru_portrait_layout.dart
- test/widgets/yaru_master_detail_page_test.dart
Pass available pane width to `YaruMasterDetailBuilder`.
This allows the tile builder to be responsive without needing a `LayoutBuilder` for each tile.
> Pass available width to YaruMasterDetailBuilder

- example/lib/example_page_items.dart
- example/lib/main.dart
- example/lib/pages/choice_chip_bar_page.dart
- lib/src/widgets/yaru_choice_chip_bar.dart
- lib/widgets.dart
I thought this is a useful wrapping around choicechips. I can use it inside MusicPod for filtering different things :)
[Bildschirmaufzeichnung vom 2023-06-19, 21-52-35.webm](https://github.com/ubuntu/yaru_widgets.dart/assets/15329494/3efac21e-2b05-4ba0-b44a-f59fac40d202)
> Add YaruChoiceChipBar

- example/lib/main.dart
- example/lib/pages/choice_chip_bar_page.dart
- lib/src/widgets/yaru_choice_chip_bar.dart
This introduces a third option "stack" for the choice chip bar. 
https://github.com/ubuntu/yaru_widgets.dart/assets/15329494/03a7bc80-f5cb-410e-98ed-d35cf6d75469
Since it changes the parameters of the widget I thought "feat!" was correct ❓
> feat: add a stack option to YaruChoiceChipBar

- .github/workflows/ci.yml
- .github/workflows/pr.yaml
Same as in yaru.dart:
- https://github.com/ubuntu/yaru.dart/pull/355
> ci: let release-please maintain the changelog

- .github/dependabot.yaml
I don't know how exactly dependabot decides between semantic vs. non-semantic commits but the first PR it opened didn't use semantic commits so try explicitly configuring it:
- #726
> chore(dependabot): configure semantic commits

- lib/src/widgets/navi_rail/yaru_navigation_page.dart
Allows pushing (named) routes onto YaruNavigationPage's internal Navigator. For example:
```dart
YaruNavigationPage(
navigatorKey: _navigatorKey,
...
onGenerateRoute: (settings) => switch (settings.name) {
'/detail' => MaterialPageRoute(
settings: settings,
builder: (_) => DetailPage(settings.arguments as Detail),
),
'/search' => MaterialPageRoute(
settings: settings,
builder: (_) => SearchPage(query: settings.arguments as String),
),
_ => null,
},
)
```
From within the navigation page:
```dart
Navigator.pushNamed(context, '/detail', arguments: detail);
```
From anywhere else such as a global search bar:
```dart
_navigatorKey.currentState!.pushNamed('/search', arguments: query);
```
> feat: expose YaruNavigationPage.navigatorKey and onGenerateRoute

- lib/src/widgets/navi_rail/yaru_navigation_page.dart
Allow launching straight to a detail route from command-line arguments, for example.
> feat: expose YaruNavigationPage.initialRoute and onUnknownRoute

- lib/src/widgets/master_detail/yaru_landscape_layout.dart
- lib/src/widgets/master_detail/yaru_master_detail_page.dart
- lib/src/widgets/master_detail/yaru_portrait_layout.dart
To bring `YaruMasterDetailPage` on par with `YaruNavigationPage`.
See also:
- https://github.com/ubuntu/yaru_widgets.dart/pull/730
- https://github.com/ubuntu/yaru_widgets.dart/pull/731
- https://github.com/ubuntu/yaru_widgets.dart/pull/732
> feat(master-detail): expose Navigator properties

- lib/src/widgets/master_detail/yaru_master_list_view.dart
A separate bottom bar works fine for about or settings dialogs and similar, but gets clumsy if one wants to have normal master tiles at the bottom. This PR makes it possible for `YaruMasterDetailPage.tileBuilder` to return spacers (and dividers) to make it possible to categorize master list items in any way desired.
```dart
final pages = <({WidgetBuilder tile, WidgetBuilder page})>[
(
tile: (_) => const YaruMasterTile(title: Text('Foo')),
page: (_) => const Center(child: Text('Foo')),
),
(
tile: (_) => const YaruMasterTile(title: Text('Bar')),
page: (_) => const Center(child: Text('Bar')),
),
(
tile: (_) => const YaruMasterTile(title: Text('Baz')),
page: (_) => const Center(child: Text('Baz')),
),
(
tile: (_) => const YaruMasterTile(title: Text('Qux')),
page: (_) => const Center(child: …
```
> feat(master-detail): allow inserting spacers and dividers

- lib/src/widgets/master_detail/yaru_master_detail_page.dart
And document that `0` and `double.infinity` can be used as breakpoints to force landscape and portrait layouts, respectively.
> feat(master-detail): expose breakpoint as widget property

- lib/src/widgets/master_detail/yaru_master_tile.dart
~~This adds a parameter to disable looking up the YaruMasterTileScope for tiles added to the list inside YMD that should not open a page.~~
~~Is this the correct approach @jpnurmi ?~~
Use case: 1 tile inside the list should open a dialog and not select/load a page
Closes #718
> fix(YaruMasterTile): let onTap override scope ontap

- lib/src/widgets/yaru_back_button.dart
- lib/src/widgets/yaru_choice_chip_bar.dart
- lib/src/widgets/yaru_close_button.dart
- lib/src/widgets/yaru_expansion_panel.dart
- lib/src/widgets/yaru_popup_menu_button.dart
- lib/src/widgets/yaru_search_field.dart
> fix: add the missing optional icon parameters

- lib/src/widgets/navi_rail/yaru_navigation_rail_item.dart
[Capture vidéo du 2023-08-11 14-07-59.webm](https://github.com/ubuntu/yaru_widgets.dart/assets/36476595/59a1ec80-2754-4b9b-a8ca-9d8db3f7d9fc)
- Add `extendedSelectedIndicator` option, which wrap the icon and the label into the selected background indicator ; ![Capture d’écran du 2023-08-11 13-43-00](https://github.com/ubuntu/yaru_widgets.dart/assets/36476595/e18f4ecb-0fb8-4d6e-8186-fb7f6a88329e) ![Capture d’écran du 2023-08-11 13-43-31](https://github.com/ubuntu/yaru_widgets.dart/assets/36476595/d635c1ac-7515-47bd-a596-0dc14ffeb39e)
- Add `borderRadius` option, to control the selected background indicator border radius. ![Capture d’écran du 2023-08-11 13-42-28](https://github.com/ubuntu/yaru_widgets.dart/assets/36476595/2dbd718e-803e-458a-90fb-5e941d3c1e4e)
Fixes #753
> feat: improve YaruNavigationRailItem

- lib/src/widgets/yaru_title_bar.dart
> fix(YaruTitleBar): foreground color is not forwarded to YaruTitleBar

- lib/src/widgets/yaru_title_bar.dart
- lib/src/widgets/yaru_window_control.dart
> fix(YaruWindowControl): colors are not exposed

- lib/src/widgets/yaru_window_control.dart
> fix(YaruWindowControl): use foreground color for disk background

- lib/src/widgets/yaru_search_field.dart
> fix: adjust search icon size

- example/lib/example.dart
> chore: update example with the new paned style

- lib/src/widgets/yaru_switch.dart
- Fix switch thumb grabbing ;
- keep active and hover state while grab.
**Before:**
[Capture vidéo du 2023-09-20 14-17-26.webm](https://github.com/ubuntu/yaru_widgets.dart/assets/36476595/3b29b0a5-3e7c-457b-aea5-92603311b4d3)
**After:**
[Capture vidéo du 2023-09-20 14-15-10.webm](https://github.com/ubuntu/yaru_widgets.dart/assets/36476595/9ed28e73-c3d0-4e45-9679-31f1f43f7f39)
> fix: natural switch thumb grab

- lib/src/widgets/yaru_tab_bar.dart
"If [TabController] is not provided, then the value of [DefaultTabController.of] will be used."
~~Need to check this first if this works~~
Works, sorry, should have tested on musicpod/real app first :) 
Also added onTap, as this is part of material tabbar api
> fix(YaruTabBar): make TabController nullable, add onTap

- lib/src/widgets/master_detail/yaru_master_list_view.dart
No visual change.
It looks like the problem comes from both `SliverFillRemaining` and `ListTile` which seems to not send its correct height when having a subtitle. I will investigate deeper because it looks like a bug.
@d-loose I will create a backport PR for 2.7, so you can get the fix before migrating to 3.2
Fixes #785
> fix: overflow in left pane of `YaruMasterDetailPage`

- lib/src/widgets/yaru_expansion_panel.dart
|       | Before | After |
|-------|--------|-------|
| Light |![grafik](https://github.com/ubuntu/yaru_widgets.dart/assets/15329494/04fb5c22-4bab-4c44-aa80-2856955ff560)|![grafik](https://github.com/ubuntu/yaru_widgets.dart/assets/15329494/60336aac-0f28-44d7-97e1-cb185fe43c1e)|
> fix(YaruExpansionPanel): use hairline dividers

- example/lib/pages/choice_chip_bar_page.dart
- lib/src/widgets/yaru_choice_chip_bar.dart
add showCheckMarks and shrinkWrap. The default is kept so this change is not critical.
Shrink wrap prevents the listview to expand if true
And showCheckMarks can disable the checkmarks
https://github.com/ubuntu/yaru_widgets.dart/assets/15329494/fe46c4c1-cc12-4965-b41f-d02dabdd291d
> feat(YaruChoiceChipBar): add more parameters

- lib/src/widgets/master_detail/yaru_landscape_layout.dart
> fix: reduce number of used scaffolds

- example/lib/pages/choice_chip_bar_page.dart
- lib/src/widgets/yaru_choice_chip_bar.dart
@Jupi007 this adds an option if you do not want the selected chips to be shown first
default stays the same in lib
> feat(YaruChoiceChipBar): add selectedFirst parameter

- lib/src/widgets/yaru_choice_chip_bar.dart
This allows to control the border color of the internal chiptheme.
This is needed because the bar includes an internal chiptheme which overwrites the one from Theme.of(context).
This internal chiptheme is needed to align the button radius to the chip radius.
Additionally this also adds options to set the background and selected background colors.
> fix(YaruChoiceChipBar): allow more parameters

- lib/src/widgets/yaru_choice_chip_bar.dart
The buttons need to take the parameters too, if they would be changed.
This fixes that and also adds an optional elevation parameter
> fix(YaruChoiceChipBar): forward parameters to buttons
