ubuntu/yaru_widgets.dart

- test/yaru_extra_options_row_test.dart
- test/yaru_options_button_test.dart
> test: add new test

- test/yaru_check_box_row_test.dart
- test/yaru_image_tile_test.dart
- test/yaru_page_container_test.dart
- test/yaru_row_test.dart
- test/yaru_single_info_row_test.dart
- test/yaru_togggle_button_row_test.dart
> test: add yaru toggleButton row test

- example/lib/yaru_master_details_page.dart
- lib/src/yaru_section.dart
> Let headers have a widget at the end if wanted

- example/lib/widgets/yaru_option_card_list.dart
- example/lib/yaru_master_details_page.dart
- example/test/widget_test.dart
- test/yaru_togggle_button_row_test.dart
PR a bit useless: just fix infos messages.
> Fix infos messages

- .github/workflows/flutter-ci.yml
Because each good repo should have some CI actions ;)
@Feichtmeier I added the `flutter format` check but I'm not sure. What do you think of?
> Add Github Action Flutter CI

- example/lib/yaru_master_details_page.dart
- lib/src/yaru_linear_progress_indicator.dart
- lib/yaru_widgets.dart
Closes #27 https://github.com/Feichtmeier/settings/issues/207
> Add YaruLinearProgressIndicator widget

- example/lib/yaru_master_details_page.dart
- lib/src/yaru_simple_dialog.dart
- lib/yaru_widgets.dart
Closes #28
See https://github.com/Feichtmeier/settings/issues/209
> Add YaruSimpleDialog widget

- lib/src/yaru_landscape_layout.dart
- lib/src/yaru_master_detail_page.dart
- lib/src/yaru_option_button.dart
- lib/src/yaru_page_container.dart
- lib/src/yaru_row.dart
- lib/src/yaru_search_app_bar.dart
- lib/src/yaru_section.dart
- lib/src/yaru_single_info_row.dart
- lib/src/yaru_slider_row.dart
- lib/src/yaru_slider_secondary.dart
- lib/src/yaru_switch_row.dart
- lib/src/yaru_toggle_buttons_row.dart
> docs: add dart docs (#3)

- example/lib/main.dart
- example/lib/yaru_home.dart
- lib/src/yaru_tabbed_page.dart
- lib/yaru_widgets.dart
\!\[ya\]\(https://user\-images.githubusercontent.com/15329494/147101579\-fd624d8a\-a9ab\-4763\-b479\-fff4272fc14e.gif\)
TODO:
Closes \#26
> YaruTabbedPage

- lib/src/yaru_tabbed_page.dart
> YaruTabbedPage: add labelColor

- lib/src/yaru_linear_progress_indicator.dart
> Use current track color for bg

- example/lib/yaru_home.dart
- lib/src/yaru_color_picker_button.dart
- lib/yaru_widgets.dart
> Add YaruColorPickerButton

- lib/src/yaru_color_picker_button.dart
Option to disable YaruColorPickerButton
> Add option to disable color picker button

- example/lib/yaru_home.dart
> improve the example by making use of YaruPage

- example/lib/yaru_home.dart
- lib/src/constants.dart
- lib/src/yaru_alert_dialog.dart
- lib/src/yaru_dialog_title.dart
- lib/yaru_widgets.dart
- extract the title to an individual widget
- add a YaruAlertDialog
> Dialog update

- example/lib/example_page_items.dart
- example/lib/main.dart
- lib/src/yaru_carousel.dart
- lib/yaru_widgets.dart
> Add yaru carousel

- lib/src/yaru_page_item_list_view.dart
> ListTiles: reduce visual density

- example/lib/pages/carousel_page.dart
- lib/src/yaru_carousel.dart
- linux/flutter/generated_plugins.cmake
> YaruCarousel: allow any widgets in the carousel

- example/lib/example_page_items.dart
- example/lib/main.dart
- example/lib/pages/color_disk_page.dart
- example/lib/theme.dart
- example/pubspec.yaml
- lib/src/yaru_color_disk.dart
- lib/yaru_widgets.dart
> Add YaruColorDisk

- example/lib/pages/color_disk_page.dart
Fix `color_disk_page` which was using old `YaruColor` from **yaru.dart**.
> Fix color_disk_page

- lib/src/yaru_wide_layout.dart
> Improve navigationrail in yaru_wide_layout

- lib/src/yaru_alert_dialog.dart
> Allow custom content padding

- lib/src/yaru_carousel.dart
> YaruCarousel: add placeIndicator option

- lib/src/yaru_carousel.dart
Add `viewportFraction` option to `YaruCarousel`.
> Add viewportFraction option to YaruCarousel

- example/lib/example_page_items.dart
- lib/src/yaru_expandable.dart
- lib/yaru_widgets.dart
https://user-images.githubusercontent.com/36476595/170832556-14718cee-5623-4124-87bc-7981d9f2cf21.mp4
@Feichtmeier Instead of a `YaruExpandableText` I did a generic `YaruExpandable` widget where you can put whatever you want :)
> Add new YaruExpandable widget

- example/lib/example_page_items.dart
- example/lib/main.dart
- example/lib/pages/round_toggle_button_page.dart
- lib/src/yaru_round_toggle_button.dart
- lib/yaru_widgets.dart
> Add YaruRoundToggleButton

- lib/src/yaru_wide_layout.dart
if no selectedItemWidget is specified
> WideLayout: fallback to itemWIdget

- lib/src/yaru_expandable.dart
https://user-images.githubusercontent.com/36476595/173413546-310d563c-c8f2-42b2-bfea-052cb6f3ea73.mp4
> YaruExpandable: add onChange callback

- lib/src/yaru_checkbox_row.dart
- lib/src/yaru_extra_option_row.dart
- lib/src/yaru_row.dart
- lib/src/yaru_section.dart
- lib/src/yaru_single_info_row.dart
- lib/src/yaru_slider_row.dart
- lib/src/yaru_switch_row.dart
- lib/src/yaru_tabbed_page.dart
- lib/src/yaru_toggle_buttons_row.dart
> Make row widgets configurable

- example/lib/pages/tabbed_page_page.dart
- lib/src/yaru_tabbed_page.dart
> Give YaruTabbedPage index on rebuild

- .github/workflows/publish.yml
- README.md
- example/.gitignore
> Web build should be used in Pages

- lib/src/yaru_search_app_bar.dart
> YaruSearchBar: improve sizes and constraints

- example/lib/main.dart
- lib/src/yaru_narrow_layout.dart
> Make YaruNarrowLayout build less complicated

- lib/src/yaru_wide_layout.dart
> Fix wide layout text regression

- example/lib/example_page_items.dart
- example/pubspec.yaml
- lib/src/animations/yaru_animated_ok_icon.dart
- lib/yaru_widgets.dart
[Capture vidéo du 23-08-2022 13:30:27.webm](https://user-images.githubusercontent.com/36476595/186147300-5dc21b80-32f8-449a-8ebc-35f0de6a286f.webm)
> Yaru animated ok icon

- lib/src/utilities/yaru_banner.dart
||Light|Dark|
|-|-|-|
|Before|![grafik](https://user-images.githubusercontent.com/15329494/186598655-76f4570a-0be3-4213-b907-71f2f595c46a.png)|![grafik](https://user-images.githubusercontent.com/15329494/186598593-ca447d27-944e-41e4-a4a3-fddb1db4289a.png)|
|After|![grafik](https://user-images.githubusercontent.com/15329494/186598410-62cd731b-6e0b-4158-9e7e-1e8b068f287e.png)|![grafik](https://user-images.githubusercontent.com/15329494/186598483-590e41dc-c726-441c-9345-2d4482713521.png)|
> YaruBanner: make the hover color gray

- lib/src/utilities/yaru_banner.dart
- lib/yaru_widgets.dart
Just export `inner_border_radius.dart`.
> Export inner_border_radius.dart

- lib/yaru_widgets.dart
Just order yaru_widgets exports.
Because it looks cleaner :)
> Order yaru_widgets exports

- lib/src/utilities/yaru_carousel.dart
[Capture vidéo du 20-09-2022 10:27:41.webm](https://user-images.githubusercontent.com/36476595/191211009-0a3a89c9-a0ca-41b6-a6f3-53be22a769da.webm)
Closes #208
> Hide control buttons when first/last page reached

- lib/src/pages/layouts/yaru_wide_layout.dart
[Bildschirmaufzeichnung vom 20.09.2022, 12:24:32.webm](https://user-images.githubusercontent.com/15329494/191234236-27177683-e7ef-441d-9275-6d6a920cf9f4.webm)
> WideLayout: add yaru transition

- example/lib/main.dart
- lib/src/pages/layouts/yaru_compact_layout.dart
- re-add scrollcontroller
- add optional background color
- readd contraints
> Comact layout fixes

- CHANGELOG.md
- pubspec.yaml
- [Frederik Feichtmeier](https://github.com/Feichtmeier)
- Comact layout fixes (#214)
> Release 1.1.5

- example/lib/pages/carousel_page.dart
|---|---|
| ![Screenshot from 2022-09-25 08-38-30](https://user-images.githubusercontent.com/140617/192131524-e4f49011-6d76-40bf-9a8a-de3723dba88e.png) | ![Screenshot from 2022-09-25 08-37-43](https://user-images.githubusercontent.com/140617/192131494-8eff0b01-7b88-4ca8-bdb8-e293cd6d6583.png) |
Ref: #200
> Carousel example: replace YaruRow with ButtonBar

- example/lib/example_page_items.dart
- example/lib/main.dart
- example/lib/pages/section_page.dart
- example/lib/widgets/dummy_section.dart
- example/lib/widgets/tile_list.dart
- lib/src/pages/rows/yaru_extra_option_row.dart
- lib/src/pages/rows/yaru_row.dart
- lib/src/pages/rows/yaru_single_info_row.dart
- lib/src/pages/rows/yaru_slider_row.dart
- lib/src/pages/rows/yaru_switch_row.dart
- lib/src/pages/rows/yaru_toggle_buttons_row.dart
- lib/src/pages/yaru_tile.dart
- lib/yaru_widgets.dart
- test/pages/rows/yaru_switch_row_test.dart
- test/pages/yaru_tile_test.dart
Even the docs suggest it's similar to ListTile. :wink:
> YaruRow: drop Row-specific properties and rename to YaruTile

- lib/src/utilities/yaru_selectable_container.dart
**Before:**
[Capture vidéo du 06-10-2022 21:31:24.webm](https://user-images.githubusercontent.com/36476595/194402637-a4c4040f-58bd-4482-bf94-855f450b5715.webm)
**After:**
[Capture vidéo du 06-10-2022 21:26:46.webm](https://user-images.githubusercontent.com/36476595/194402635-0a9e22ff-d82f-4d74-8150-f6d32ca67901.webm)
> Use animation in YaruSelectableContainer

- example/lib/main.dart
- lib/src/pages/layouts/yaru_compact_layout.dart
- lib/src/pages/layouts/yaru_navigation_rail.dart
Same as #248 but for YaruCompactLayout.
> YaruCompactLayout: replace "page item" with indexed builders

- lib/src/utilities/yaru_banner.dart
> YaruBanner: fix text style regression

- lib/src/pages/layouts/yaru_compact_layout.dart
- lib/src/pages/layouts/yaru_compact_layout_theme.dart
- lib/yaru_widgets.dart
So far, it only has page transitions. More will come later.
No visual changes except that it's now possible to customize the page transitions.
> Add initial YaryCompactLayoutTheme

- lib/src/pages/layouts/yaru_landscape_layout.dart
- lib/src/pages/layouts/yaru_navigation_rail.dart
**YaruNavigationRail:** Fix text align.
**LandscapeLayout:** Add rtl support for resizing, and fix separator position.
Closes #269
> Layouts: better rtl support

- lib/src/layouts/yaru_compact_layout.dart
|-|-|-|
|Compact| ![Capture d’écran du 2022-10-13 12-52-08](https://user-images.githubusercontent.com/36476595/195578499-53045a60-252d-41df-aed8-68ef05eba2b9.png) | ![Capture d’écran du 2022-10-13 12-51-50](https://user-images.githubusercontent.com/36476595/195578494-0fb946e4-780e-404a-9e80-f024fc96d6c8.png) |
|Labelled| ![Capture d’écran du 2022-10-13 12-48-05](https://user-images.githubusercontent.com/36476595/195578488-8619e92f-4827-41a3-94a3-e6ae2bc853ae.png) | ![Capture d’écran du 2022-10-13 12-47-46](https://user-images.githubusercontent.com/36476595/195578482-39bbe98c-4294-4540-a87b-8e338f3abdef.png) |
|Extended| ![Capture d’écran du 2022-10-13 12-53-16](https://user-images.githubusercontent.com/36476595/195578506-d0e2f0f2-16ad-4245-8334-13583ea66ca9.png) | …
> YaruCompactLayout: use thinner scrollbar

- example/lib/main.dart
- lib/src/utilities/yaru_carousel.dart
https://github.com/flutter/flutter/pull/89944 introduced a new `PointerDeviceKind.trackpad` value.
Fixes: #287
> Example: fix touchpad/gesture scrolling on Wayland

- lib/src/controls/yaru_icon_button.dart
> YaruIconButton: handle disabled state

- lib/src/utilities/yaru_banner.dart
|-|-|-|
|Light|![grafik](https://user-images.githubusercontent.com/15329494/196464254-2a4fb04f-a553-4c40-8253-d186ea233019.png)|![grafik](https://user-images.githubusercontent.com/15329494/196464091-8fa2e414-8f77-42f3-a633-da6ae5c289b6.png)|
> YaruBanner: add iconpadding

- example/lib/pages/popup_page.dart
- example/pubspec.yaml
- lib/src/controls/yaru_popup_menu_button.dart
https://user-images.githubusercontent.com/15329494/197391005-98bbfd15-8aa1-440c-b0ae-810c28213279.mp4
> YaruPopupMenuButton: add multi check item

- example/lib/pages/popup_page.dart
- example/pubspec.yaml
Will do the code snippets in a different PR for all pages
> Example: clean up popup page

- lib/src/utilities/yaru_carousel.dart
> CarousselController: do not dispose

- example/lib/pages/check_button_page.dart
- lib/src/controls/yaru_check_button.dart
Handle null value in `YaruCheckButton`.
Fixes #341
> YaruCheckButton throw an exception with tristate

- lib/src/controls/yaru_popup_menu_button.dart
**Before:**
[Capture vidéo du 2022-10-25 22-33-17.webm](https://user-images.githubusercontent.com/36476595/197876331-fcb504ce-8d50-489b-ae5b-2a6fd88c92e5.webm)
**After:**
[Capture vidéo du 2022-10-25 22-30-30.webm](https://user-images.githubusercontent.com/36476595/197876344-e2eb8ea1-e8bd-45ec-8e5f-adee30cb6f98.webm)
> _YaruCheckedPopupMenuItemState: show changing state

- CHANGELOG.md
- pubspec.yaml
- [Paul Kepinski](https://github.com/Jupi007)
-  Add YaruSwitch (#362)
> Release 2.0.0-beta-1

- example/lib/example_page_items.dart
- example/lib/main.dart
Have to give a snippet url is a bit containing imo, and so should be optional.
> Example: make snippet button optional

- example/lib/main.dart
> Center the code-snippet button

- example/lib/code_snippet_button.dart
- example/lib/example.dart
- example/lib/example_model.dart
- example/lib/main.dart
- example/linux/my_application.cc
- example/pubspec.yaml
- snap/snapcraft.yaml
Example:
- use provider
- use connectivy plus
- use ubuntu service
- move code snippet button and example into their own files
https://user-images.githubusercontent.com/15329494/201095062-f8e1c074-34b5-47fd-a60c-4cea2a68b1f1.mp4
> Example: clean up and check for ConnectionState

- example/lib/code_snippet_button.dart
> Example: fix typo and padding

- example/lib/pages/carousel_page.dart
- example/lib/pages/section_page.dart
- lib/src/pages/yaru_section.dart
> YaruSection: replace internal Column with an arbitrary child Widget

- lib/src/controls/yaru_checkbox.dart
- lib/src/controls/yaru_radio.dart
- lib/src/controls/yaru_switch.dart
- lib/src/controls/yaru_togglable.dart
I mostly reused material controls comments.
Fixes #374
> Add comments on new controls widgets

- .github/PULL_REQUEST_TEMPLATE.md
|-|-|-|
|Light| | |
|Dark| | |
> GitHub: improve PR template

- lib/src/controls/yaru_radio_button.dart
- test/controls/yaru_radio_button_test.dart
https://user-images.githubusercontent.com/36476595/202846890-a2b8f244-53df-42f2-b7b4-00e3b8a38497.mp4
Fixes #400
> Add togglable support to YaruRadioButton

- lib/src/controls/yaru_title_bar.dart
|-|-|-|
|Light| | |
|Dark| | |
> YaruTitleBar: expose background color

- lib/src/controls/yaru_toggle_button.dart
- lib/src/controls/yaru_toggle_button_theme.dart
|-|-|-|
|Light| | |
|Dark| | |
> Toggle buttons: themable title and subtitle text style

- lib/src/layouts/yaru_navigation_rail_item.dart
> Add missing comments in YaruNavigationRailItem

- lib/src/controls/yaru_toggle_button.dart
- lib/src/controls/yaru_toggle_button_layout.dart
|-|-|-|
|Light| | |
|Dark| | |
> Fix typo in _YaruToggleButtonLayout name

- lib/src/utilities/yaru_banner.dart
|-|-|-|
|Light| | |
|Dark| | |
> YaruBanner: remove unused bannerWidth property

- example/lib/pages/banner_page.dart
- lib/src/utilities/yaru_banner.dart
- https://github.com/ubuntu-flutter-community/software/pull/578
> Remove YaruBanner.thirdTitle

- lib/src/controls/yaru_close_button.dart
- lib/src/layouts/yaru_navigation_rail_item.dart
- lib/src/utilities/yaru_carousel.dart
> Fix typo: "alignement"

- example/lib/example.dart
[settings-dialog.webm](https://user-images.githubusercontent.com/140617/205386505-998600ee-8b61-43d2-ac7f-390238f690f8.webm)
> Example: settings dialog

- lib/src/utilities/yaru_banner.dart
|-|-|-|
|Light| | |
|Dark| | |
> YaruBanner: add onHover callback

- example/lib/pages/banner_page.dart
- lib/src/utilities/yaru_banner.dart
https://user-images.githubusercontent.com/15329494/205485861-216d221f-1b0f-4352-bb1e-fa61af3dbac9.mp4
|-|-|-|
|Light| | |
|Dark| | |
> YaruBanner: forward onHover to .tile constructor

- lib/src/layouts/yaru_navigation_page.dart
- lib/src/layouts/yaru_navigation_page_theme.dart
> Rename YaruCompactLayoutTheme(Data) to YaruNavigationPageTheme(Data)

- lib/src/layouts/yaru_navigation_page.dart
Tested it, and this was indeed the source of your problem @Feichtmeier 
Fixes #456
> Forward initialIndex to default YaruPageController

- lib/src/layouts/yaru_navigation_page.dart
- test/pages/yaru_navigation_page_test.dart
Same as #468 but for NavigationPage.
> NavigationPage: fix controller updates

- lib/src/controls/yaru_togglable.dart
- lib/src/controls/yaru_window_control.dart
Reverts ubuntu/yaru_widgets.dart#520
> Revert "Remove all RepaintBoundary widgets"

- lib/src/pages/yaru_tile.dart
**Before:**
**After:**
Closes #559
> Fix YaruTile wrong text color

- lib/src/extensions/border_radius_extension.dart
> YaruBorderRadiusExtension

- CHANGELOG.md
- pubspec.yaml
* Fix: YaruBanners bg color with upgrading yaru to 0.5.1 by @Feichtmeier in https://github.com/ubuntu/yaru_widgets.dart/pull/575
> Release 2.0.1

- lib/src/controls/yaru_checkbox.dart
- lib/src/controls/yaru_radio.dart
- lib/src/controls/yaru_switch.dart
> Add diagnosticable properties to togglable widgets

- lib/src/pages/yaru_section.dart
> YaruSection: fix unbounded height

- pubspec.yaml
Same as ubuntu/yaru.dart#276
| yaru_widgets | yaru_colors |
|---|---|
| ![image](https://user-images.githubusercontent.com/140617/216816835-a10e4c03-8dfd-4972-9902-5f3d6dd2e3e9.png) | ![image](https://user-images.githubusercontent.com/140617/216816882-c97e1dab-c17f-4670-a02e-c545918d2b46.png) |
> pubspec: add missing issue tracker link

- example/lib/example_page_items.dart
- example/lib/pages/page_indicator.dart
- lib/src/widgets/yaru_carousel.dart
- lib/src/widgets/yaru_page_indicator.dart
- lib/widgets.dart
[Capture vidéo du 2023-02-05 19-43-56.webm](https://user-images.githubusercontent.com/36476595/216838646-6e308dd3-025f-45b7-bc08-4259bd5f509c.webm)
Fixes #582
> Introduce YaruPageIndicator

- lib/src/widgets/yaru_carousel.dart
@jpnurmi I a bit unsure about `return Future.any([]);` what do you think of?
**Before:**
[Capture vidéo du 2023-02-05 20-04-30.webm](https://user-images.githubusercontent.com/36476595/216839521-6bf013ad-e8fd-468f-9cf0-76651515896c.webm)
**After:**
https://user-images.githubusercontent.com/36476595/216843171-60c5a8aa-d870-419b-aee2-b44a214101c5.mp4
Fixes #595
> YaruCarousel: fix laggy animation on multiple clicks

- lib/src/widgets/master_detail/yaru_landscape_layout.dart
- lib/src/widgets/master_detail/yaru_master_list_view.dart
- lib/src/widgets/master_detail/yaru_master_tile.dart
- lib/src/widgets/yaru_banner.dart
- lib/src/widgets/yaru_close_button.dart
- lib/src/widgets/yaru_draggable.dart
- lib/src/widgets/yaru_expandable.dart
- lib/src/widgets/yaru_popup_menu_button.dart
> Use Flutter's callback typedefs

- lib/src/widgets/yaru_togglable.dart
[Capture vidéo du 2023-02-08 12-47-20.webm](https://user-images.githubusercontent.com/36476595/217521746-ca3d0909-1459-4ff0-a5b0-5b79aa54e8c1.webm)
Fixes #603
> Missing mixed->checked checkbox animation

- lib/src/widgets/yaru_popup_menu_button.dart
|-|-|-|
|Light| | |
|Dark| | |
> YaruPopupMenuButton: make radius changeable

- CHANGELOG.md
- pubspec.yaml
* Switch to yaru_window by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/618
* YaruPopupMenuButton: replace borderRadius with style by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/620
> Release v2.1.0

- CHANGELOG.md
- pubspec.yaml
* YaruPageIndicator: add custom scale parameters by @d-loose in https://github.com/ubuntu/yaru_widgets.dart/pull/624
* YaruPopupMenuButton: use outline color by @Feichtmeier in https://github.com/ubuntu/yaru_widgets.dart/pull/626
> Release 2.1.1

- lib/src/widgets/yaru_switch.dart
Let's introduce this new dev branch by drop deprecated stuff :D
> Drop deprecated YaruSwitch.checkmarkColor property

- example/pubspec.yaml
Large shadows were noticed in https://github.com/ubuntu/yaru.dart/issues/294#issuecomment-1445031772.
> Example: upgrade handy_window to ^0.3.0

- .github/workflows/nightly.yml
This helps to update the golden images whenever there are indirect changes from yaru.dart, for example.
> CI: add nightly job to update golden images (PR)

- CHANGELOG.md
- pubspec.yaml
* Update goldens with new dependencies by @Jupi007 in https://github.com/ubuntu/yaru_widgets.dart/pull/630
* Drop YaruSwitch.checkmarkColor earlier (2.2.0) by @Jupi007 in https://github.com/ubuntu/yaru_widgets.dart/pull/629
* Introduce YaruPageIndicatorTheme by @Jupi007 in https://github.com/ubuntu/yaru_widgets.dart/pull/632
* Update PR template by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/640
* Example: upgrade handy_window to ^0.3.0 by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/637
* Example: add macOS by @jpnurmi in https://github.com/ubuntu/yaru_widgets.dart/pull/635
* Update PR template for the new branch organization by @Jupi007 in https://github.com/ubuntu/yaru_widgets.dart/pull/646
* Cherry pick 2.2-dev into main by @Jupi007 in …
> Release 2.2.0

- lib/src/widgets/master_detail/yaru_master_detail_page.dart
- lib/src/widgets/navi_rail/yaru_navigation_page.dart
> Add `emptyBuilder`

- lib/src/widgets/yaru_page_indicator.dart
> YaruPageIndicator: fix RTL layout

- CHANGELOG.md
- pubspec.yaml
* #676
* #681
* #682
* #684
* #685
> Release 2.3.0

- CHANGELOG.md
- pubspec.yaml
> Release v2.3.1

- lib/src/widgets/yaru_expandable.dart
**Before:**
[Capture vidéo du 2023-04-13 19-58-16.webm](https://user-images.githubusercontent.com/36476595/231844743-664e4b61-2715-48e2-871a-726114cd9268.webm)
**After:**
[Capture vidéo du 2023-04-13 19-55-02.webm](https://user-images.githubusercontent.com/36476595/231844753-e4348018-8eaf-439c-9f45-2064e5db3fb8.webm)
> YaruExpandable: update isExpanded property

- CHANGELOG.md
- pubspec.yaml
> Release v2.4.1

- lib/src/widgets/master_detail/yaru_landscape_layout.dart
- lib/src/widgets/master_detail/yaru_master_detail_page.dart
- lib/src/widgets/master_detail/yaru_master_list_view.dart
- lib/src/widgets/master_detail/yaru_portrait_layout.dart
> Rename `YaruMasterDetailBuilder` into `YaruMasterTileBuilder`

- lib/src/widgets/master_detail/yaru_master_tile.dart
> Drop double `YaruMasterTileScope` retrieval

- lib/src/widgets/yaru_choice_chip_bar.dart
@Jupi007 @jpnurmi 
What would you prefer as the default radius?
This:
or that:
> feat: improve YaruChipChoice parameters

- .github/workflows/ci.yml
- .github/workflows/pr.yaml
- .github/workflows/release.yaml
https://github.com/ubuntu-flutter-community/actions
> ci: reuse pr title & release actions from ufc/actions

- lib/src/widgets/master_detail/yaru_landscape_layout.dart
- lib/src/widgets/master_detail/yaru_master_detail_page.dart
- lib/src/widgets/master_detail/yaru_portrait_layout.dart
[Screencast from 2023-07-13 20-37-41.webm](https://github.com/ubuntu/yaru_widgets.dart/assets/140617/aed2f24b-7076-42b5-af33-a38cd8e0f05e)
Close: #512
> fix(master-detail): retain state when switching orientation

- example/lib/code_snippet_button.dart
- example/pubspec.yaml
- pubspec.yaml
> chore!: update yaru icons

- pubspec.yaml
> chore: relax yaru_icons version constraint

- .github/workflows/publish.yaml
> fix: publish CI flutter version

- lib/src/widgets/yaru_choice_chip_bar.dart
[Bildschirmaufzeichnung vom 2023-08-21, 11-45-34.webm](https://github.com/ubuntu/yaru_widgets.dart/assets/15329494/756e85c4-9dea-45ba-9fb8-c59d1fce99d7)
> feat: add clear on select flag to choice chip bar

- example/pubspec.yaml
- pubspec.yaml
> Update yaru to 1.1.0

- example/lib/example_page_items.dart
- example/lib/pages/tab_bar_page.dart
- example/windows/runner/flutter_window.cpp
- lib/src/widgets/yaru_tab_bar.dart
- lib/widgets.dart
https://github.com/ubuntu/yaru_widgets.dart/assets/15329494/4e131ca6-7836-4ce0-a541-43a7ca66d284
@Jupi007 which parameters should we expose?
> feat: add YaruTabBar

- example/pubspec.yaml
- pubspec.yaml
> chore: update yaru.dart dependency

- .github/workflows/nightly.yml
> chore: update nightly CI flutter version

- pubspec.yaml
> chore: update yaru.dart

- lib/src/widgets/yaru_choice_chip_bar.dart
[Bildschirmaufzeichnung vom 2024-01-04, 12-06-17.webm](https://github.com/ubuntu/yaru_widgets.dart/assets/15329494/2c4f2ffd-3d0b-4a86-a9e6-c899f199cc90)
Fixes #817
> fix: choice chip nav buttons block mouse
